//
// Generated By:JAX-WS RI IBM 2.1.6 in JDK 6 (JAXB RI IBM JAXB 2.1.10 in JDK 6)
//


package cl.metlife.conciliacion.ws.connectormut;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the cl.metlife.conciliacion.ws.connector2 package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _ConciliarPagoResponse_QNAME = new QName("http://ws.conciliacion.hdp.metlife.cl/", "ConciliarPagoResponse");
    private final static QName _ConciliarPago_QNAME = new QName("http://ws.conciliacion.hdp.metlife.cl/", "ConciliarPago");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: cl.metlife.conciliacion.ws.connector2
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ConciliarPago }
     * 
     */
    public ConciliarPago createConciliarPago() {
        return new ConciliarPago();
    }

    /**
     * Create an instance of {@link ConciliarPagoResponse }
     * 
     */
    public ConciliarPagoResponse createConciliarPagoResponse() {
        return new ConciliarPagoResponse();
    }

    /**
     * Create an instance of {@link ResultadoConciliacion }
     * 
     */
    public ResultadoConciliacion createResultadoConciliacion() {
        return new ResultadoConciliacion();
    }

    /**
     * Create an instance of {@link Pago }
     * 
     */
    public Pago createPago() {
        return new Pago();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ConciliarPagoResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ws.conciliacion.hdp.metlife.cl/", name = "ConciliarPagoResponse")
    public JAXBElement<ConciliarPagoResponse> createConciliarPagoResponse(ConciliarPagoResponse value) {
        return new JAXBElement<ConciliarPagoResponse>(_ConciliarPagoResponse_QNAME, ConciliarPagoResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ConciliarPago }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ws.conciliacion.hdp.metlife.cl/", name = "ConciliarPago")
    public JAXBElement<ConciliarPago> createConciliarPago(ConciliarPago value) {
        return new JAXBElement<ConciliarPago>(_ConciliarPago_QNAME, ConciliarPago.class, null, value);
    }

}
