//
// Generated By:JAX-WS RI IBM 2.1.6 in JDK 6 (JAXB RI IBM JAXB 2.1.10 in JDK 6)
//


package cl.qr.ws2;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for boleta2 complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="boleta2">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="idBoleta" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="vencimientoBoleta" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
 *         &lt;element name="descripcion" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="InfoAdicional" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="monto" type="{http://www.w3.org/2001/XMLSchema}double" minOccurs="0"/>
 *         &lt;element name="divisa" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="lineaDeNegocio" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="urlNotificacion" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "boleta2", namespace = "http://ws.botonpago.hdp.metlife.cl/", propOrder = {
    "idBoleta",
    "vencimientoBoleta",
    "descripcion",
    "infoAdicional",
    "monto",
    "divisa",
    "lineaDeNegocio",
    "urlNotificacion"
})
public class Boleta2 {

    @XmlElement(required = true)
    protected String idBoleta;
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar vencimientoBoleta;
    protected String descripcion;
    @XmlElement(name = "InfoAdicional")
    protected String infoAdicional;
    protected Double monto;
    protected String divisa;
    @XmlElement(required = true)
    protected String lineaDeNegocio;
    protected String urlNotificacion;

    /**
     * Gets the value of the idBoleta property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIdBoleta() {
        return idBoleta;
    }

    /**
     * Sets the value of the idBoleta property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIdBoleta(String value) {
        this.idBoleta = value;
    }

    /**
     * Gets the value of the vencimientoBoleta property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getVencimientoBoleta() {
        return vencimientoBoleta;
    }

    /**
     * Sets the value of the vencimientoBoleta property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setVencimientoBoleta(XMLGregorianCalendar value) {
        this.vencimientoBoleta = value;
    }

    /**
     * Gets the value of the descripcion property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDescripcion() {
        return descripcion;
    }

    /**
     * Sets the value of the descripcion property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDescripcion(String value) {
        this.descripcion = value;
    }

    /**
     * Gets the value of the infoAdicional property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInfoAdicional() {
        return infoAdicional;
    }

    /**
     * Sets the value of the infoAdicional property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInfoAdicional(String value) {
        this.infoAdicional = value;
    }

    /**
     * Gets the value of the monto property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getMonto() {
        return monto;
    }

    /**
     * Sets the value of the monto property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setMonto(Double value) {
        this.monto = value;
    }

    /**
     * Gets the value of the divisa property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDivisa() {
        return divisa;
    }

    /**
     * Sets the value of the divisa property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDivisa(String value) {
        this.divisa = value;
    }

    /**
     * Gets the value of the lineaDeNegocio property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLineaDeNegocio() {
        return lineaDeNegocio;
    }

    /**
     * Sets the value of the lineaDeNegocio property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLineaDeNegocio(String value) {
        this.lineaDeNegocio = value;
    }

    /**
     * Gets the value of the urlNotificacion property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUrlNotificacion() {
        return urlNotificacion;
    }

    /**
     * Sets the value of the urlNotificacion property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUrlNotificacion(String value) {
        this.urlNotificacion = value;
    }

}
