//
// Generated By:JAX-WS RI IBM 2.1.6 in JDK 6 (JAXB RI IBM JAXB 2.1.10 in JDK 6)
//


package cl.qr.ws2;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for BuscarPagosResponse complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="BuscarPagosResponse">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="RespuestaBuscarPagos" type="{http://ws.botonpago.hdp.metlife.cl/}listaPagos" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "BuscarPagosResponse", namespace = "http://ws.botonpago.hdp.metlife.cl/", propOrder = {
    "respuestaBuscarPagos"
})
public class BuscarPagosResponse {

    @XmlElement(name = "RespuestaBuscarPagos")
    protected ListaPagos respuestaBuscarPagos;

    /**
     * Gets the value of the respuestaBuscarPagos property.
     * 
     * @return
     *     possible object is
     *     {@link ListaPagos }
     *     
     */
    public ListaPagos getRespuestaBuscarPagos() {
        return respuestaBuscarPagos;
    }

    /**
     * Sets the value of the respuestaBuscarPagos property.
     * 
     * @param value
     *     allowed object is
     *     {@link ListaPagos }
     *     
     */
    public void setRespuestaBuscarPagos(ListaPagos value) {
        this.respuestaBuscarPagos = value;
    }

}
