//
// Generated By:JAX-WS RI IBM 2.1.6 in JDK 6 (JAXB RI IBM JAXB 2.1.10 in JDK 6)
//


package cl.qr.ws2;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for BuscarPagos complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="BuscarPagos">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="CriterioBusqueda" type="{http://ws.botonpago.hdp.metlife.cl/}criterioBusqueda" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "BuscarPagos", namespace = "http://ws.botonpago.hdp.metlife.cl/", propOrder = {
    "criterioBusqueda"
})
public class BuscarPagos {

    @XmlElement(name = "CriterioBusqueda")
    protected CriterioBusqueda criterioBusqueda;

    /**
     * Gets the value of the criterioBusqueda property.
     * 
     * @return
     *     possible object is
     *     {@link CriterioBusqueda }
     *     
     */
    public CriterioBusqueda getCriterioBusqueda() {
        return criterioBusqueda;
    }

    /**
     * Sets the value of the criterioBusqueda property.
     * 
     * @param value
     *     allowed object is
     *     {@link CriterioBusqueda }
     *     
     */
    public void setCriterioBusqueda(CriterioBusqueda value) {
        this.criterioBusqueda = value;
    }

}
