//
// Generated By:JAX-WS RI IBM 2.1.6 in JDK 6 (JAXB RI IBM JAXB 2.1.10 in JDK 6)
//


package cl.qr.ws2;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ConsultarEstadoPagoResponse complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ConsultarEstadoPagoResponse">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="EstadoPago" type="{http://ws.botonpago.hdp.metlife.cl/}estadoPago" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ConsultarEstadoPagoResponse", namespace = "http://ws.botonpago.hdp.metlife.cl/", propOrder = {
    "estadoPago"
})
public class ConsultarEstadoPagoResponse {

    @XmlElement(name = "EstadoPago")
    protected EstadoPago estadoPago;

    /**
     * Gets the value of the estadoPago property.
     * 
     * @return
     *     possible object is
     *     {@link EstadoPago }
     *     
     */
    public EstadoPago getEstadoPago() {
        return estadoPago;
    }

    /**
     * Sets the value of the estadoPago property.
     * 
     * @param value
     *     allowed object is
     *     {@link EstadoPago }
     *     
     */
    public void setEstadoPago(EstadoPago value) {
        this.estadoPago = value;
    }

}
