//
// Generated By:JAX-WS RI IBM 2.1.6 in JDK 6 (JAXB RI IBM JAXB 2.1.10 in JDK 6)
//


package cl.qr.ws2;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for informacionFlujoPagoV2 complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="informacionFlujoPagoV2">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="idPago" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="urlEntradaFlujoPago" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="montoTotal" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *         &lt;element name="token" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="urlLanding" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "informacionFlujoPagoV2", namespace = "http://ws.botonpago.hdp.metlife.cl/", propOrder = {
    "idPago",
    "urlEntradaFlujoPago",
    "montoTotal",
    "token",
    "urlLanding"
})
public class InformacionFlujoPagoV2 {

    protected int idPago;
    @XmlElement(required = true)
    protected String urlEntradaFlujoPago;
    protected double montoTotal;
    @XmlElement(required = true)
    protected String token;
    @XmlElement(required = true)
    protected String urlLanding;

    /**
     * Gets the value of the idPago property.
     * 
     */
    public int getIdPago() {
        return idPago;
    }

    /**
     * Sets the value of the idPago property.
     * 
     */
    public void setIdPago(int value) {
        this.idPago = value;
    }

    /**
     * Gets the value of the urlEntradaFlujoPago property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUrlEntradaFlujoPago() {
        return urlEntradaFlujoPago;
    }

    /**
     * Sets the value of the urlEntradaFlujoPago property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUrlEntradaFlujoPago(String value) {
        this.urlEntradaFlujoPago = value;
    }

    /**
     * Gets the value of the montoTotal property.
     * 
     */
    public double getMontoTotal() {
        return montoTotal;
    }

    /**
     * Sets the value of the montoTotal property.
     * 
     */
    public void setMontoTotal(double value) {
        this.montoTotal = value;
    }

    /**
     * Gets the value of the token property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getToken() {
        return token;
    }

    /**
     * Sets the value of the token property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setToken(String value) {
        this.token = value;
    }

    /**
     * Gets the value of the urlLanding property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUrlLanding() {
        return urlLanding;
    }

    /**
     * Sets the value of the urlLanding property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUrlLanding(String value) {
        this.urlLanding = value;
    }

}
