//
// Generated By:JAX-WS RI IBM 2.1.6 in JDK 6 (JAXB RI IBM JAXB 2.1.10 in JDK 6)
//


package cl.qr.ws2;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for informacionPago complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="informacionPago">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="boletas" type="{http://ws.botonpago.hdp.metlife.cl/}boleta" maxOccurs="unbounded"/>
 *         &lt;element name="cliente" type="{http://ws.botonpago.hdp.metlife.cl/}cliente"/>
 *         &lt;element name="urlFinPago" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="idCuentaDestinoPago" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "informacionPago", namespace = "http://ws.botonpago.hdp.metlife.cl/", propOrder = {
    "boletas",
    "cliente",
    "urlFinPago",
    "idCuentaDestinoPago"
})
public class InformacionPago {

    @XmlElement(required = true)
    protected List<Boleta> boletas;
    @XmlElement(required = true)
    protected Cliente cliente;
    @XmlElement(required = true)
    protected String urlFinPago;
    protected int idCuentaDestinoPago;

    /**
     * Gets the value of the boletas property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the boletas property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getBoletas().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Boleta }
     * 
     * 
     */
    public List<Boleta> getBoletas() {
        if (boletas == null) {
            boletas = new ArrayList<Boleta>();
        }
        return this.boletas;
    }

    /**
     * Gets the value of the cliente property.
     * 
     * @return
     *     possible object is
     *     {@link Cliente }
     *     
     */
    public Cliente getCliente() {
        return cliente;
    }

    /**
     * Sets the value of the cliente property.
     * 
     * @param value
     *     allowed object is
     *     {@link Cliente }
     *     
     */
    public void setCliente(Cliente value) {
        this.cliente = value;
    }

    /**
     * Gets the value of the urlFinPago property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUrlFinPago() {
        return urlFinPago;
    }

    /**
     * Sets the value of the urlFinPago property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUrlFinPago(String value) {
        this.urlFinPago = value;
    }

    /**
     * Gets the value of the idCuentaDestinoPago property.
     * 
     */
    public int getIdCuentaDestinoPago() {
        return idCuentaDestinoPago;
    }

    /**
     * Sets the value of the idCuentaDestinoPago property.
     * 
     */
    public void setIdCuentaDestinoPago(int value) {
        this.idCuentaDestinoPago = value;
    }

}
