//
// Generated By:JAX-WS RI IBM 2.1.6 in JDK 6 (JAXB RI IBM JAXB 2.1.10 in JDK 6)
//


package cl.qr.ws2;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for informacionPagoV4 complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="informacionPagoV4">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="item" type="{http://ws.botonpago.hdp.metlife.cl/}item" maxOccurs="unbounded"/>
 *         &lt;element name="cliente" type="{http://ws.botonpago.hdp.metlife.cl/}cliente2"/>
 *         &lt;element name="urlFinPago" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="pagoRecurrente" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="formaDePagoForzada" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="idSkin" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="lineaDeNegocio" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "informacionPagoV4", namespace = "http://ws.botonpago.hdp.metlife.cl/", propOrder = {
    "item",
    "cliente",
    "urlFinPago",
    "pagoRecurrente",
    "formaDePagoForzada",
    "idSkin",
    "lineaDeNegocio"
})
public class InformacionPagoV4 {

    @XmlElement(required = true)
    protected List<Item> item;
    @XmlElement(required = true)
    protected Cliente2 cliente;
    @XmlElement(required = true)
    protected String urlFinPago;
    protected boolean pagoRecurrente;
    protected String formaDePagoForzada;
    protected String idSkin;
    protected String lineaDeNegocio;

    /**
     * Gets the value of the item property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the item property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getItem().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Item }
     * 
     * 
     */
    public List<Item> getItem() {
        if (item == null) {
            item = new ArrayList<Item>();
        }
        return this.item;
    }

    /**
     * Gets the value of the cliente property.
     * 
     * @return
     *     possible object is
     *     {@link Cliente2 }
     *     
     */
    public Cliente2 getCliente() {
        return cliente;
    }

    /**
     * Sets the value of the cliente property.
     * 
     * @param value
     *     allowed object is
     *     {@link Cliente2 }
     *     
     */
    public void setCliente(Cliente2 value) {
        this.cliente = value;
    }

    /**
     * Gets the value of the urlFinPago property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUrlFinPago() {
        return urlFinPago;
    }

    /**
     * Sets the value of the urlFinPago property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUrlFinPago(String value) {
        this.urlFinPago = value;
    }

    /**
     * Gets the value of the pagoRecurrente property.
     * 
     */
    public boolean isPagoRecurrente() {
        return pagoRecurrente;
    }

    /**
     * Sets the value of the pagoRecurrente property.
     * 
     */
    public void setPagoRecurrente(boolean value) {
        this.pagoRecurrente = value;
    }

    /**
     * Gets the value of the formaDePagoForzada property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFormaDePagoForzada() {
        return formaDePagoForzada;
    }

    /**
     * Sets the value of the formaDePagoForzada property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFormaDePagoForzada(String value) {
        this.formaDePagoForzada = value;
    }

    /**
     * Gets the value of the idSkin property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIdSkin() {
        return idSkin;
    }

    /**
     * Sets the value of the idSkin property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIdSkin(String value) {
        this.idSkin = value;
    }

    /**
     * Gets the value of the lineaDeNegocio property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLineaDeNegocio() {
        return lineaDeNegocio;
    }

    /**
     * Sets the value of the lineaDeNegocio property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLineaDeNegocio(String value) {
        this.lineaDeNegocio = value;
    }

}
