//
// Generated By:JAX-WS RI IBM 2.1.6 in JDK 6 (JAXB RI IBM JAXB 2.1.10 in JDK 6)
//


package cl.qr.ws2;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the cl.qr.ws2 package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _ListarLineasDeNegocioResponse_QNAME = new QName("http://ws.botonpago.hdp.metlife.cl/", "ListarLineasDeNegocioResponse");
    private final static QName _ConsultarEstadoPago_QNAME = new QName("http://ws.botonpago.hdp.metlife.cl/", "ConsultarEstadoPago");
    private final static QName _ListarLineasDeNegocio_QNAME = new QName("http://ws.botonpago.hdp.metlife.cl/", "ListarLineasDeNegocio");
    private final static QName _ConsultarEstadoPagoResponse_QNAME = new QName("http://ws.botonpago.hdp.metlife.cl/", "ConsultarEstadoPagoResponse");
    private final static QName _SolicitarPagoResponse_QNAME = new QName("http://ws.botonpago.hdp.metlife.cl/", "SolicitarPagoResponse");
    private final static QName _SolicitarPago_QNAME = new QName("http://ws.botonpago.hdp.metlife.cl/", "SolicitarPago");
    private final static QName _BuscarPagosResponse_QNAME = new QName("http://ws.botonpago.hdp.metlife.cl/", "BuscarPagosResponse");
    private final static QName _Exception_QNAME = new QName("http://ws.botonpago.hdp.metlife.cl/", "Exception");
    private final static QName _SolicitarPagoV2_QNAME = new QName("http://ws.botonpago.hdp.metlife.cl/", "SolicitarPagoV2");
    private final static QName _SolicitarPagoV3_QNAME = new QName("http://ws.botonpago.hdp.metlife.cl/", "SolicitarPagoV3");
    private final static QName _SolicitarPagoV4_QNAME = new QName("http://ws.botonpago.hdp.metlife.cl/", "SolicitarPagoV4");
    private final static QName _SolicitarPagoV2Response_QNAME = new QName("http://ws.botonpago.hdp.metlife.cl/", "SolicitarPagoV2Response");
    private final static QName _SolicitarPagoV3Response_QNAME = new QName("http://ws.botonpago.hdp.metlife.cl/", "SolicitarPagoV3Response");
    private final static QName _ListarFormasPago_QNAME = new QName("http://ws.botonpago.hdp.metlife.cl/", "ListarFormasPago");
    private final static QName _BuscarPagos_QNAME = new QName("http://ws.botonpago.hdp.metlife.cl/", "BuscarPagos");
    private final static QName _ListarFormasPagoResponse_QNAME = new QName("http://ws.botonpago.hdp.metlife.cl/", "ListarFormasPagoResponse");
    private final static QName _SolicitarPagoV4Response_QNAME = new QName("http://ws.botonpago.hdp.metlife.cl/", "SolicitarPagoV4Response");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: cl.qr.ws2
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link SolicitarPagoV4Response }
     * 
     */
    public SolicitarPagoV4Response createSolicitarPagoV4Response() {
        return new SolicitarPagoV4Response();
    }

    /**
     * Create an instance of {@link InformacionPagoV3 }
     * 
     */
    public InformacionPagoV3 createInformacionPagoV3() {
        return new InformacionPagoV3();
    }

    /**
     * Create an instance of {@link SolicitarPagoV4 }
     * 
     */
    public SolicitarPagoV4 createSolicitarPagoV4() {
        return new SolicitarPagoV4();
    }

    /**
     * Create an instance of {@link EstadoPago }
     * 
     */
    public EstadoPago createEstadoPago() {
        return new EstadoPago();
    }

    /**
     * Create an instance of {@link BuscarPagos }
     * 
     */
    public BuscarPagos createBuscarPagos() {
        return new BuscarPagos();
    }

    /**
     * Create an instance of {@link ListarFormasPagoResponse }
     * 
     */
    public ListarFormasPagoResponse createListarFormasPagoResponse() {
        return new ListarFormasPagoResponse();
    }

    /**
     * Create an instance of {@link Cliente2 }
     * 
     */
    public Cliente2 createCliente2() {
        return new Cliente2();
    }

    /**
     * Create an instance of {@link InformacionPagoV2 }
     * 
     */
    public InformacionPagoV2 createInformacionPagoV2() {
        return new InformacionPagoV2();
    }

    /**
     * Create an instance of {@link InformacionPago }
     * 
     */
    public InformacionPago createInformacionPago() {
        return new InformacionPago();
    }

    /**
     * Create an instance of {@link ListarLineasDeNegocio }
     * 
     */
    public ListarLineasDeNegocio createListarLineasDeNegocio() {
        return new ListarLineasDeNegocio();
    }

    /**
     * Create an instance of {@link SolicitarPagoV2Response }
     * 
     */
    public SolicitarPagoV2Response createSolicitarPagoV2Response() {
        return new SolicitarPagoV2Response();
    }

    /**
     * Create an instance of {@link SolicitarPagoV3 }
     * 
     */
    public SolicitarPagoV3 createSolicitarPagoV3() {
        return new SolicitarPagoV3();
    }

    /**
     * Create an instance of {@link InformacionFlujoPago }
     * 
     */
    public InformacionFlujoPago createInformacionFlujoPago() {
        return new InformacionFlujoPago();
    }

    /**
     * Create an instance of {@link ListarFormasPago }
     * 
     */
    public ListarFormasPago createListarFormasPago() {
        return new ListarFormasPago();
    }

    /**
     * Create an instance of {@link InstitucionPago }
     * 
     */
    public InstitucionPago createInstitucionPago() {
        return new InstitucionPago();
    }

    /**
     * Create an instance of {@link ListarLineasDeNegocioResponse }
     * 
     */
    public ListarLineasDeNegocioResponse createListarLineasDeNegocioResponse() {
        return new ListarLineasDeNegocioResponse();
    }

    /**
     * Create an instance of {@link PagoHistorico }
     * 
     */
    public PagoHistorico createPagoHistorico() {
        return new PagoHistorico();
    }

    /**
     * Create an instance of {@link CriterioBusqueda }
     * 
     */
    public CriterioBusqueda createCriterioBusqueda() {
        return new CriterioBusqueda();
    }

    /**
     * Create an instance of {@link SolicitarPago }
     * 
     */
    public SolicitarPago createSolicitarPago() {
        return new SolicitarPago();
    }

    /**
     * Create an instance of {@link SolicitarPagoResponse }
     * 
     */
    public SolicitarPagoResponse createSolicitarPagoResponse() {
        return new SolicitarPagoResponse();
    }

    /**
     * Create an instance of {@link ListaPagos }
     * 
     */
    public ListaPagos createListaPagos() {
        return new ListaPagos();
    }

    /**
     * Create an instance of {@link Boleta2 }
     * 
     */
    public Boleta2 createBoleta2() {
        return new Boleta2();
    }

    /**
     * Create an instance of {@link SolicitarPagoV3Response }
     * 
     */
    public SolicitarPagoV3Response createSolicitarPagoV3Response() {
        return new SolicitarPagoV3Response();
    }

    /**
     * Create an instance of {@link SolicitarPagoV2 }
     * 
     */
    public SolicitarPagoV2 createSolicitarPagoV2() {
        return new SolicitarPagoV2();
    }

    /**
     * Create an instance of {@link InformacionFlujoPagoV2 }
     * 
     */
    public InformacionFlujoPagoV2 createInformacionFlujoPagoV2() {
        return new InformacionFlujoPagoV2();
    }

    /**
     * Create an instance of {@link Exception }
     * 
     */
    public Exception createException() {
        return new Exception();
    }

    /**
     * Create an instance of {@link BuscarPagosResponse }
     * 
     */
    public BuscarPagosResponse createBuscarPagosResponse() {
        return new BuscarPagosResponse();
    }

    /**
     * Create an instance of {@link ConsultarEstadoPagoResponse }
     * 
     */
    public ConsultarEstadoPagoResponse createConsultarEstadoPagoResponse() {
        return new ConsultarEstadoPagoResponse();
    }

    /**
     * Create an instance of {@link ConsultarEstadoPago }
     * 
     */
    public ConsultarEstadoPago createConsultarEstadoPago() {
        return new ConsultarEstadoPago();
    }

    /**
     * Create an instance of {@link Boleta }
     * 
     */
    public Boleta createBoleta() {
        return new Boleta();
    }

    /**
     * Create an instance of {@link Item }
     * 
     */
    public Item createItem() {
        return new Item();
    }

    /**
     * Create an instance of {@link InformacionPagoV4 }
     * 
     */
    public InformacionPagoV4 createInformacionPagoV4() {
        return new InformacionPagoV4();
    }

    /**
     * Create an instance of {@link Cliente }
     * 
     */
    public Cliente createCliente() {
        return new Cliente();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ListarLineasDeNegocioResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ws.botonpago.hdp.metlife.cl/", name = "ListarLineasDeNegocioResponse")
    public JAXBElement<ListarLineasDeNegocioResponse> createListarLineasDeNegocioResponse(ListarLineasDeNegocioResponse value) {
        return new JAXBElement<ListarLineasDeNegocioResponse>(_ListarLineasDeNegocioResponse_QNAME, ListarLineasDeNegocioResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ConsultarEstadoPago }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ws.botonpago.hdp.metlife.cl/", name = "ConsultarEstadoPago")
    public JAXBElement<ConsultarEstadoPago> createConsultarEstadoPago(ConsultarEstadoPago value) {
        return new JAXBElement<ConsultarEstadoPago>(_ConsultarEstadoPago_QNAME, ConsultarEstadoPago.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ListarLineasDeNegocio }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ws.botonpago.hdp.metlife.cl/", name = "ListarLineasDeNegocio")
    public JAXBElement<ListarLineasDeNegocio> createListarLineasDeNegocio(ListarLineasDeNegocio value) {
        return new JAXBElement<ListarLineasDeNegocio>(_ListarLineasDeNegocio_QNAME, ListarLineasDeNegocio.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ConsultarEstadoPagoResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ws.botonpago.hdp.metlife.cl/", name = "ConsultarEstadoPagoResponse")
    public JAXBElement<ConsultarEstadoPagoResponse> createConsultarEstadoPagoResponse(ConsultarEstadoPagoResponse value) {
        return new JAXBElement<ConsultarEstadoPagoResponse>(_ConsultarEstadoPagoResponse_QNAME, ConsultarEstadoPagoResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SolicitarPagoResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ws.botonpago.hdp.metlife.cl/", name = "SolicitarPagoResponse")
    public JAXBElement<SolicitarPagoResponse> createSolicitarPagoResponse(SolicitarPagoResponse value) {
        return new JAXBElement<SolicitarPagoResponse>(_SolicitarPagoResponse_QNAME, SolicitarPagoResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SolicitarPago }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ws.botonpago.hdp.metlife.cl/", name = "SolicitarPago")
    public JAXBElement<SolicitarPago> createSolicitarPago(SolicitarPago value) {
        return new JAXBElement<SolicitarPago>(_SolicitarPago_QNAME, SolicitarPago.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BuscarPagosResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ws.botonpago.hdp.metlife.cl/", name = "BuscarPagosResponse")
    public JAXBElement<BuscarPagosResponse> createBuscarPagosResponse(BuscarPagosResponse value) {
        return new JAXBElement<BuscarPagosResponse>(_BuscarPagosResponse_QNAME, BuscarPagosResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Exception }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ws.botonpago.hdp.metlife.cl/", name = "Exception")
    public JAXBElement<Exception> createException(Exception value) {
        return new JAXBElement<Exception>(_Exception_QNAME, Exception.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SolicitarPagoV2 }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ws.botonpago.hdp.metlife.cl/", name = "SolicitarPagoV2")
    public JAXBElement<SolicitarPagoV2> createSolicitarPagoV2(SolicitarPagoV2 value) {
        return new JAXBElement<SolicitarPagoV2>(_SolicitarPagoV2_QNAME, SolicitarPagoV2 .class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SolicitarPagoV3 }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ws.botonpago.hdp.metlife.cl/", name = "SolicitarPagoV3")
    public JAXBElement<SolicitarPagoV3> createSolicitarPagoV3(SolicitarPagoV3 value) {
        return new JAXBElement<SolicitarPagoV3>(_SolicitarPagoV3_QNAME, SolicitarPagoV3 .class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SolicitarPagoV4 }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ws.botonpago.hdp.metlife.cl/", name = "SolicitarPagoV4")
    public JAXBElement<SolicitarPagoV4> createSolicitarPagoV4(SolicitarPagoV4 value) {
        return new JAXBElement<SolicitarPagoV4>(_SolicitarPagoV4_QNAME, SolicitarPagoV4 .class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SolicitarPagoV2Response }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ws.botonpago.hdp.metlife.cl/", name = "SolicitarPagoV2Response")
    public JAXBElement<SolicitarPagoV2Response> createSolicitarPagoV2Response(SolicitarPagoV2Response value) {
        return new JAXBElement<SolicitarPagoV2Response>(_SolicitarPagoV2Response_QNAME, SolicitarPagoV2Response.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SolicitarPagoV3Response }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ws.botonpago.hdp.metlife.cl/", name = "SolicitarPagoV3Response")
    public JAXBElement<SolicitarPagoV3Response> createSolicitarPagoV3Response(SolicitarPagoV3Response value) {
        return new JAXBElement<SolicitarPagoV3Response>(_SolicitarPagoV3Response_QNAME, SolicitarPagoV3Response.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ListarFormasPago }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ws.botonpago.hdp.metlife.cl/", name = "ListarFormasPago")
    public JAXBElement<ListarFormasPago> createListarFormasPago(ListarFormasPago value) {
        return new JAXBElement<ListarFormasPago>(_ListarFormasPago_QNAME, ListarFormasPago.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BuscarPagos }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ws.botonpago.hdp.metlife.cl/", name = "BuscarPagos")
    public JAXBElement<BuscarPagos> createBuscarPagos(BuscarPagos value) {
        return new JAXBElement<BuscarPagos>(_BuscarPagos_QNAME, BuscarPagos.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ListarFormasPagoResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ws.botonpago.hdp.metlife.cl/", name = "ListarFormasPagoResponse")
    public JAXBElement<ListarFormasPagoResponse> createListarFormasPagoResponse(ListarFormasPagoResponse value) {
        return new JAXBElement<ListarFormasPagoResponse>(_ListarFormasPagoResponse_QNAME, ListarFormasPagoResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SolicitarPagoV4Response }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ws.botonpago.hdp.metlife.cl/", name = "SolicitarPagoV4Response")
    public JAXBElement<SolicitarPagoV4Response> createSolicitarPagoV4Response(SolicitarPagoV4Response value) {
        return new JAXBElement<SolicitarPagoV4Response>(_SolicitarPagoV4Response_QNAME, SolicitarPagoV4Response.class, null, value);
    }

}
