//
// Generated By:JAX-WS RI IBM 2.1.6 in JDK 6 (JAXB RI IBM JAXB 2.1.10 in JDK 6)
//


package cl.qr.ws2;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

@WebService(name = "PagoWS", targetNamespace = "http://ws.botonpago.hdp.metlife.cl/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface PagoWS {


    /**
     * 
     * @param informacionPago
     * @return
     *     returns cl.qr.ws2.InformacionFlujoPago
     * @throws Exception_Exception
     */
    @WebMethod(operationName = "SolicitarPago", action = "SolicitarPago")
    @WebResult(name = "RespuestaSolicitudPago", targetNamespace = "")
    @RequestWrapper(localName = "SolicitarPago", targetNamespace = "http://ws.botonpago.hdp.metlife.cl/", className = "cl.qr.ws2.SolicitarPago")
    @ResponseWrapper(localName = "SolicitarPagoResponse", targetNamespace = "http://ws.botonpago.hdp.metlife.cl/", className = "cl.qr.ws2.SolicitarPagoResponse")
    public InformacionFlujoPago solicitarPago(
        @WebParam(name = "InformacionPago", targetNamespace = "")
        InformacionPago informacionPago)
        throws Exception_Exception
    ;

    /**
     * 
     * @param informacionPagoV2
     * @return
     *     returns cl.qr.ws2.InformacionFlujoPagoV2
     * @throws Exception_Exception
     */
    @WebMethod(operationName = "SolicitarPagoV2", action = "SolicitarPagoV2")
    @WebResult(name = "RespuestaSolicitudPago", targetNamespace = "")
    @RequestWrapper(localName = "SolicitarPagoV2", targetNamespace = "http://ws.botonpago.hdp.metlife.cl/", className = "cl.qr.ws2.SolicitarPagoV2")
    @ResponseWrapper(localName = "SolicitarPagoV2Response", targetNamespace = "http://ws.botonpago.hdp.metlife.cl/", className = "cl.qr.ws2.SolicitarPagoV2Response")
    public InformacionFlujoPagoV2 solicitarPagoV2(
        @WebParam(name = "InformacionPagoV2", targetNamespace = "")
        InformacionPagoV2 informacionPagoV2)
        throws Exception_Exception
    ;

    /**
     * 
     * @param informacionPagoV3
     * @return
     *     returns cl.qr.ws2.InformacionFlujoPagoV2
     * @throws Exception_Exception
     */
    @WebMethod(operationName = "SolicitarPagoV3", action = "SolicitarPagoV3")
    @WebResult(name = "RespuestaSolicitudPago", targetNamespace = "")
    @RequestWrapper(localName = "SolicitarPagoV3", targetNamespace = "http://ws.botonpago.hdp.metlife.cl/", className = "cl.qr.ws2.SolicitarPagoV3")
    @ResponseWrapper(localName = "SolicitarPagoV3Response", targetNamespace = "http://ws.botonpago.hdp.metlife.cl/", className = "cl.qr.ws2.SolicitarPagoV3Response")
    public InformacionFlujoPagoV2 solicitarPagoV3(
        @WebParam(name = "InformacionPagoV3", targetNamespace = "")
        InformacionPagoV3 informacionPagoV3)
        throws Exception_Exception
    ;

    /**
     * 
     * @param informacionPagoV4
     * @return
     *     returns cl.qr.ws2.InformacionFlujoPagoV2
     * @throws Exception_Exception
     */
    @WebMethod(operationName = "SolicitarPagoV4", action = "SolicitarPagoV4")
    @WebResult(name = "RespuestaSolicitudPago", targetNamespace = "")
    @RequestWrapper(localName = "SolicitarPagoV4", targetNamespace = "http://ws.botonpago.hdp.metlife.cl/", className = "cl.qr.ws2.SolicitarPagoV4")
    @ResponseWrapper(localName = "SolicitarPagoV4Response", targetNamespace = "http://ws.botonpago.hdp.metlife.cl/", className = "cl.qr.ws2.SolicitarPagoV4Response")
    public InformacionFlujoPagoV2 solicitarPagoV4(
        @WebParam(name = "InformacionPagoV4", targetNamespace = "")
        InformacionPagoV4 informacionPagoV4)
        throws Exception_Exception
    ;

    /**
     * 
     * @param criterioBusqueda
     * @return
     *     returns cl.qr.ws2.ListaPagos
     * @throws Exception_Exception
     */
    @WebMethod(operationName = "BuscarPagos", action = "BuscarPagos")
    @WebResult(name = "RespuestaBuscarPagos", targetNamespace = "")
    @RequestWrapper(localName = "BuscarPagos", targetNamespace = "http://ws.botonpago.hdp.metlife.cl/", className = "cl.qr.ws2.BuscarPagos")
    @ResponseWrapper(localName = "BuscarPagosResponse", targetNamespace = "http://ws.botonpago.hdp.metlife.cl/", className = "cl.qr.ws2.BuscarPagosResponse")
    public ListaPagos buscarPagos(
        @WebParam(name = "CriterioBusqueda", targetNamespace = "")
        CriterioBusqueda criterioBusqueda)
        throws Exception_Exception
    ;

    /**
     * 
     * @param informacionPagoV2
     * @return
     *     returns java.util.List<cl.qr.ws2.InstitucionPago>
     * @throws Exception_Exception
     */
    @WebMethod(operationName = "ListarFormasPago", action = "ListarFormasPago")
    @WebResult(name = "ListaRecaudadores", targetNamespace = "")
    @RequestWrapper(localName = "ListarFormasPago", targetNamespace = "http://ws.botonpago.hdp.metlife.cl/", className = "cl.qr.ws2.ListarFormasPago")
    @ResponseWrapper(localName = "ListarFormasPagoResponse", targetNamespace = "http://ws.botonpago.hdp.metlife.cl/", className = "cl.qr.ws2.ListarFormasPagoResponse")
    public List<InstitucionPago> listarFormasPago(
        @WebParam(name = "InformacionPagoV2", targetNamespace = "")
        InformacionPagoV2 informacionPagoV2)
        throws Exception_Exception
    ;

    /**
     * 
     * @return
     *     returns java.util.List<java.lang.String>
     * @throws Exception_Exception
     */
    @WebMethod(operationName = "ListarLineasDeNegocio", action = "ListarLineasDeNegocio")
    @WebResult(name = "LineasDeNegocio", targetNamespace = "")
    @RequestWrapper(localName = "ListarLineasDeNegocio", targetNamespace = "http://ws.botonpago.hdp.metlife.cl/", className = "cl.qr.ws2.ListarLineasDeNegocio")
    @ResponseWrapper(localName = "ListarLineasDeNegocioResponse", targetNamespace = "http://ws.botonpago.hdp.metlife.cl/", className = "cl.qr.ws2.ListarLineasDeNegocioResponse")
    public List<String> listarLineasDeNegocio()
        throws Exception_Exception
    ;

    /**
     * 
     * @param idPago
     * @return
     *     returns cl.qr.ws2.EstadoPago
     * @throws Exception_Exception
     */
    @WebMethod(operationName = "ConsultarEstadoPago", action = "ConsultarEstadoPago")
    @WebResult(name = "EstadoPago", targetNamespace = "")
    @RequestWrapper(localName = "ConsultarEstadoPago", targetNamespace = "http://ws.botonpago.hdp.metlife.cl/", className = "cl.qr.ws2.ConsultarEstadoPago")
    @ResponseWrapper(localName = "ConsultarEstadoPagoResponse", targetNamespace = "http://ws.botonpago.hdp.metlife.cl/", className = "cl.qr.ws2.ConsultarEstadoPagoResponse")
    public EstadoPago consultarEstadoPago(
        @WebParam(name = "IDPago", targetNamespace = "")
        Integer idPago)
        throws Exception_Exception
    ;

}
