//
// Generated By:JAX-WS RI IBM 2.1.6 in JDK 6 (JAXB RI IBM JAXB 2.1.10 in JDK 6)
//


package cl.qr.ws2;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;

@WebServiceClient(name = "PagoWS", targetNamespace = "http://ws.botonpago.hdp.metlife.cl/", wsdlLocation = "http://13.56.78.181:80/BotonDePagoIntranet/PagoWS/PagoWS.wsdl")
public class PagoWS_Service
    extends Service
{

    private final static URL PAGOWS_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(cl.qr.ws2.PagoWS_Service.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = cl.qr.ws2.PagoWS_Service.class.getResource(".");
            url = new URL(baseUrl, "http://13.56.78.181:80/BotonDePagoIntranet/PagoWS/PagoWS.wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'http://13.56.78.181:80/BotonDePagoIntranet/PagoWS/PagoWS.wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        PAGOWS_WSDL_LOCATION = url;
    }

    public PagoWS_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public PagoWS_Service() {
        super(PAGOWS_WSDL_LOCATION, new QName("http://ws.botonpago.hdp.metlife.cl/", "PagoWS"));
    }

    /**
     * 
     * @return
     *     returns PagoWS
     */
    @WebEndpoint(name = "Pago")
    public PagoWS getPago() {
        return super.getPort(new QName("http://ws.botonpago.hdp.metlife.cl/", "Pago"), PagoWS.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns PagoWS
     */
    @WebEndpoint(name = "Pago")
    public PagoWS getPago(WebServiceFeature... features) {
        return super.getPort(new QName("http://ws.botonpago.hdp.metlife.cl/", "Pago"), PagoWS.class, features);
    }

}
