//
// Generated By:JAX-WS RI IBM 2.1.6 in JDK 6 (JAXB RI IBM JAXB 2.1.10 in JDK 6)
//


package cl.qr.ws2;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for SolicitarPagoV3 complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="SolicitarPagoV3">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="InformacionPagoV3" type="{http://ws.botonpago.hdp.metlife.cl/}informacionPagoV3" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SolicitarPagoV3", namespace = "http://ws.botonpago.hdp.metlife.cl/", propOrder = {
    "informacionPagoV3"
})
public class SolicitarPagoV3 {

    @XmlElement(name = "InformacionPagoV3")
    protected InformacionPagoV3 informacionPagoV3;

    /**
     * Gets the value of the informacionPagoV3 property.
     * 
     * @return
     *     possible object is
     *     {@link InformacionPagoV3 }
     *     
     */
    public InformacionPagoV3 getInformacionPagoV3() {
        return informacionPagoV3;
    }

    /**
     * Sets the value of the informacionPagoV3 property.
     * 
     * @param value
     *     allowed object is
     *     {@link InformacionPagoV3 }
     *     
     */
    public void setInformacionPagoV3(InformacionPagoV3 value) {
        this.informacionPagoV3 = value;
    }

}
