//
// Generated By:JAX-WS RI IBM 2.1.6 in JDK 6 (JAXB RI IBM JAXB 2.1.10 in JDK 6)
//


package cl.metlife.hdp.botonpago.dawsclient;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for addPaymentInfoToInvoiceResponse complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="addPaymentInfoToInvoiceResponse">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="saved" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "addPaymentInfoToInvoiceResponse", namespace = "http://daws.botonpago.hdp.metlife.cl/", propOrder = {
    "saved"
})
public class AddPaymentInfoToInvoiceResponse {

    protected boolean saved;

    /**
     * Gets the value of the saved property.
     * 
     */
    public boolean isSaved() {
        return saved;
    }

    /**
     * Sets the value of the saved property.
     * 
     */
    public void setSaved(boolean value) {
        this.saved = value;
    }

}
