//
// Generated By:JAX-WS RI IBM 2.1.6 in JDK 6 (JAXB RI IBM JAXB 2.1.10 in JDK 6)
//


package cl.metlife.hdp.botonpago.dawsclient;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for archivosConciliacion complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="archivosConciliacion">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="estadoProceso" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="fechaConc" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
 *         &lt;element name="idArchivoConc" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *         &lt;element name="institucionesDePago" type="{http://daws.botonpago.hdp.metlife.cl/}institucionesDePago" minOccurs="0"/>
 *         &lt;element name="logs" type="{http://daws.botonpago.hdp.metlife.cl/}log" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="nombreArchivoConc" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="pagos" type="{http://daws.botonpago.hdp.metlife.cl/}pago" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="rutaArchivoConc" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="usuario" type="{http://daws.botonpago.hdp.metlife.cl/}usuario" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "archivosConciliacion", namespace = "http://daws.botonpago.hdp.metlife.cl/", propOrder = {
    "estadoProceso",
    "fechaConc",
    "idArchivoConc",
    "institucionesDePago",
    "logs",
    "nombreArchivoConc",
    "pagos",
    "rutaArchivoConc",
    "usuario"
})
public class ArchivosConciliacion {

    protected String estadoProceso;
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar fechaConc;
    protected long idArchivoConc;
    protected InstitucionesDePago institucionesDePago;
    @XmlElement(nillable = true)
    protected List<Log> logs;
    protected String nombreArchivoConc;
    @XmlElement(nillable = true)
    protected List<Pago> pagos;
    protected String rutaArchivoConc;
    protected Usuario usuario;

    /**
     * Gets the value of the estadoProceso property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEstadoProceso() {
        return estadoProceso;
    }

    /**
     * Sets the value of the estadoProceso property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEstadoProceso(String value) {
        this.estadoProceso = value;
    }

    /**
     * Gets the value of the fechaConc property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getFechaConc() {
        return fechaConc;
    }

    /**
     * Sets the value of the fechaConc property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setFechaConc(XMLGregorianCalendar value) {
        this.fechaConc = value;
    }

    /**
     * Gets the value of the idArchivoConc property.
     * 
     */
    public long getIdArchivoConc() {
        return idArchivoConc;
    }

    /**
     * Sets the value of the idArchivoConc property.
     * 
     */
    public void setIdArchivoConc(long value) {
        this.idArchivoConc = value;
    }

    /**
     * Gets the value of the institucionesDePago property.
     * 
     * @return
     *     possible object is
     *     {@link InstitucionesDePago }
     *     
     */
    public InstitucionesDePago getInstitucionesDePago() {
        return institucionesDePago;
    }

    /**
     * Sets the value of the institucionesDePago property.
     * 
     * @param value
     *     allowed object is
     *     {@link InstitucionesDePago }
     *     
     */
    public void setInstitucionesDePago(InstitucionesDePago value) {
        this.institucionesDePago = value;
    }

    /**
     * Gets the value of the logs property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the logs property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getLogs().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Log }
     * 
     * 
     */
    public List<Log> getLogs() {
        if (logs == null) {
            logs = new ArrayList<Log>();
        }
        return this.logs;
    }

    /**
     * Gets the value of the nombreArchivoConc property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNombreArchivoConc() {
        return nombreArchivoConc;
    }

    /**
     * Sets the value of the nombreArchivoConc property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNombreArchivoConc(String value) {
        this.nombreArchivoConc = value;
    }

    /**
     * Gets the value of the pagos property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the pagos property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPagos().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Pago }
     * 
     * 
     */
    public List<Pago> getPagos() {
        if (pagos == null) {
            pagos = new ArrayList<Pago>();
        }
        return this.pagos;
    }

    /**
     * Gets the value of the rutaArchivoConc property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRutaArchivoConc() {
        return rutaArchivoConc;
    }

    /**
     * Sets the value of the rutaArchivoConc property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRutaArchivoConc(String value) {
        this.rutaArchivoConc = value;
    }

    /**
     * Gets the value of the usuario property.
     * 
     * @return
     *     possible object is
     *     {@link Usuario }
     *     
     */
    public Usuario getUsuario() {
        return usuario;
    }

    /**
     * Sets the value of the usuario property.
     * 
     * @param value
     *     allowed object is
     *     {@link Usuario }
     *     
     */
    public void setUsuario(Usuario value) {
        this.usuario = value;
    }

}
