//
// Generated By:JAX-WS RI IBM 2.1.6 in JDK 6 (JAXB RI IBM JAXB 2.1.10 in JDK 6)
//


package cl.metlife.hdp.botonpago.dawsclient;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for botonInstitucionesPago complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="botonInstitucionesPago">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="botonConvenios" type="{http://daws.botonpago.hdp.metlife.cl/}botonConvenio" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="botonInstitucionesPagoXmls" type="{http://daws.botonpago.hdp.metlife.cl/}botonInstitucionesPagoXml" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="id" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="kit" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="nombre" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="prioridad" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="servletInicioPago" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="urlLogo" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "botonInstitucionesPago", namespace = "http://daws.botonpago.hdp.metlife.cl/", propOrder = {
    "botonConvenios",
    "botonInstitucionesPagoXmls",
    "id",
    "kit",
    "nombre",
    "prioridad",
    "servletInicioPago",
    "urlLogo"
})
public class BotonInstitucionesPago {

    @XmlElement(nillable = true)
    protected List<BotonConvenio> botonConvenios;
    @XmlElement(nillable = true)
    protected List<BotonInstitucionesPagoXml> botonInstitucionesPagoXmls;
    protected int id;
    protected String kit;
    protected String nombre;
    protected int prioridad;
    protected String servletInicioPago;
    protected String urlLogo;

    /**
     * Gets the value of the botonConvenios property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the botonConvenios property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getBotonConvenios().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link BotonConvenio }
     * 
     * 
     */
    public List<BotonConvenio> getBotonConvenios() {
        if (botonConvenios == null) {
            botonConvenios = new ArrayList<BotonConvenio>();
        }
        return this.botonConvenios;
    }

    /**
     * Gets the value of the botonInstitucionesPagoXmls property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the botonInstitucionesPagoXmls property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getBotonInstitucionesPagoXmls().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link BotonInstitucionesPagoXml }
     * 
     * 
     */
    public List<BotonInstitucionesPagoXml> getBotonInstitucionesPagoXmls() {
        if (botonInstitucionesPagoXmls == null) {
            botonInstitucionesPagoXmls = new ArrayList<BotonInstitucionesPagoXml>();
        }
        return this.botonInstitucionesPagoXmls;
    }

    /**
     * Gets the value of the id property.
     * 
     */
    public int getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     */
    public void setId(int value) {
        this.id = value;
    }

    /**
     * Gets the value of the kit property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getKit() {
        return kit;
    }

    /**
     * Sets the value of the kit property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setKit(String value) {
        this.kit = value;
    }

    /**
     * Gets the value of the nombre property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNombre() {
        return nombre;
    }

    /**
     * Sets the value of the nombre property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNombre(String value) {
        this.nombre = value;
    }

    /**
     * Gets the value of the prioridad property.
     * 
     */
    public int getPrioridad() {
        return prioridad;
    }

    /**
     * Sets the value of the prioridad property.
     * 
     */
    public void setPrioridad(int value) {
        this.prioridad = value;
    }

    /**
     * Gets the value of the servletInicioPago property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getServletInicioPago() {
        return servletInicioPago;
    }

    /**
     * Sets the value of the servletInicioPago property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setServletInicioPago(String value) {
        this.servletInicioPago = value;
    }

    /**
     * Gets the value of the urlLogo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUrlLogo() {
        return urlLogo;
    }

    /**
     * Sets the value of the urlLogo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUrlLogo(String value) {
        this.urlLogo = value;
    }

}
