//
// Generated By:JAX-WS RI IBM 2.1.6 in JDK 6 (JAXB RI IBM JAXB 2.1.10 in JDK 6)
//


package cl.metlife.hdp.botonpago.dawsclient;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for botonPago complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="botonPago">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="botonAccesos" type="{http://daws.botonpago.hdp.metlife.cl/}botonAcceso" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="botonBoletas" type="{http://daws.botonpago.hdp.metlife.cl/}botonBoleta" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="botonConvenio" type="{http://daws.botonpago.hdp.metlife.cl/}botonConvenio" minOccurs="0"/>
 *         &lt;element name="botonEstado" type="{http://daws.botonpago.hdp.metlife.cl/}botonEstado" minOccurs="0"/>
 *         &lt;element name="botonLineasDeNegocio" type="{http://daws.botonpago.hdp.metlife.cl/}botonLineasDeNegocio" minOccurs="0"/>
 *         &lt;element name="campaign" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="clienteBean" type="{http://daws.botonpago.hdp.metlife.cl/}cliente" minOccurs="0"/>
 *         &lt;element name="codigoAutorizacion" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="codigoTransaccion" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="horaCreacion" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
 *         &lt;element name="horaEstado" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
 *         &lt;element name="id" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="montoTotal" type="{http://www.w3.org/2001/XMLSchema}double" minOccurs="0"/>
 *         &lt;element name="razonRechazo" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="urlFinPago" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="vecesPagado" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="version" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "botonPago", namespace = "http://daws.botonpago.hdp.metlife.cl/", propOrder = {
    "botonAccesos",
    "botonBoletas",
    "botonConvenio",
    "botonEstado",
    "botonLineasDeNegocio",
    "campaign",
    "clienteBean",
    "codigoAutorizacion",
    "codigoTransaccion",
    "horaCreacion",
    "horaEstado",
    "id",
    "montoTotal",
    "razonRechazo",
    "urlFinPago",
    "vecesPagado",
    "version"
})
public class BotonPago {

    @XmlElement(nillable = true)
    protected List<BotonAcceso> botonAccesos;
    @XmlElement(nillable = true)
    protected List<BotonBoleta> botonBoletas;
    protected BotonConvenio botonConvenio;
    protected BotonEstado botonEstado;
    protected BotonLineasDeNegocio botonLineasDeNegocio;
    protected String campaign;
    protected Cliente clienteBean;
    protected String codigoAutorizacion;
    protected String codigoTransaccion;
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar horaCreacion;
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar horaEstado;
    protected int id;
    protected Double montoTotal;
    protected String razonRechazo;
    protected String urlFinPago;
    protected int vecesPagado;
    protected int version;

    /**
     * Gets the value of the botonAccesos property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the botonAccesos property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getBotonAccesos().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link BotonAcceso }
     * 
     * 
     */
    public List<BotonAcceso> getBotonAccesos() {
        if (botonAccesos == null) {
            botonAccesos = new ArrayList<BotonAcceso>();
        }
        return this.botonAccesos;
    }

    /**
     * Gets the value of the botonBoletas property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the botonBoletas property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getBotonBoletas().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link BotonBoleta }
     * 
     * 
     */
    public List<BotonBoleta> getBotonBoletas() {
        if (botonBoletas == null) {
            botonBoletas = new ArrayList<BotonBoleta>();
        }
        return this.botonBoletas;
    }

    /**
     * Gets the value of the botonConvenio property.
     * 
     * @return
     *     possible object is
     *     {@link BotonConvenio }
     *     
     */
    public BotonConvenio getBotonConvenio() {
        return botonConvenio;
    }

    /**
     * Sets the value of the botonConvenio property.
     * 
     * @param value
     *     allowed object is
     *     {@link BotonConvenio }
     *     
     */
    public void setBotonConvenio(BotonConvenio value) {
        this.botonConvenio = value;
    }

    /**
     * Gets the value of the botonEstado property.
     * 
     * @return
     *     possible object is
     *     {@link BotonEstado }
     *     
     */
    public BotonEstado getBotonEstado() {
        return botonEstado;
    }

    /**
     * Sets the value of the botonEstado property.
     * 
     * @param value
     *     allowed object is
     *     {@link BotonEstado }
     *     
     */
    public void setBotonEstado(BotonEstado value) {
        this.botonEstado = value;
    }

    /**
     * Gets the value of the botonLineasDeNegocio property.
     * 
     * @return
     *     possible object is
     *     {@link BotonLineasDeNegocio }
     *     
     */
    public BotonLineasDeNegocio getBotonLineasDeNegocio() {
        return botonLineasDeNegocio;
    }

    /**
     * Sets the value of the botonLineasDeNegocio property.
     * 
     * @param value
     *     allowed object is
     *     {@link BotonLineasDeNegocio }
     *     
     */
    public void setBotonLineasDeNegocio(BotonLineasDeNegocio value) {
        this.botonLineasDeNegocio = value;
    }

    /**
     * Gets the value of the campaign property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCampaign() {
        return campaign;
    }

    /**
     * Sets the value of the campaign property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCampaign(String value) {
        this.campaign = value;
    }

    /**
     * Gets the value of the clienteBean property.
     * 
     * @return
     *     possible object is
     *     {@link Cliente }
     *     
     */
    public Cliente getClienteBean() {
        return clienteBean;
    }

    /**
     * Sets the value of the clienteBean property.
     * 
     * @param value
     *     allowed object is
     *     {@link Cliente }
     *     
     */
    public void setClienteBean(Cliente value) {
        this.clienteBean = value;
    }

    /**
     * Gets the value of the codigoAutorizacion property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCodigoAutorizacion() {
        return codigoAutorizacion;
    }

    /**
     * Sets the value of the codigoAutorizacion property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCodigoAutorizacion(String value) {
        this.codigoAutorizacion = value;
    }

    /**
     * Gets the value of the codigoTransaccion property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCodigoTransaccion() {
        return codigoTransaccion;
    }

    /**
     * Sets the value of the codigoTransaccion property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCodigoTransaccion(String value) {
        this.codigoTransaccion = value;
    }

    /**
     * Gets the value of the horaCreacion property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getHoraCreacion() {
        return horaCreacion;
    }

    /**
     * Sets the value of the horaCreacion property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setHoraCreacion(XMLGregorianCalendar value) {
        this.horaCreacion = value;
    }

    /**
     * Gets the value of the horaEstado property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getHoraEstado() {
        return horaEstado;
    }

    /**
     * Sets the value of the horaEstado property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setHoraEstado(XMLGregorianCalendar value) {
        this.horaEstado = value;
    }

    /**
     * Gets the value of the id property.
     * 
     */
    public int getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     */
    public void setId(int value) {
        this.id = value;
    }

    /**
     * Gets the value of the montoTotal property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getMontoTotal() {
        return montoTotal;
    }

    /**
     * Sets the value of the montoTotal property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setMontoTotal(Double value) {
        this.montoTotal = value;
    }

    /**
     * Gets the value of the razonRechazo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRazonRechazo() {
        return razonRechazo;
    }

    /**
     * Sets the value of the razonRechazo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRazonRechazo(String value) {
        this.razonRechazo = value;
    }

    /**
     * Gets the value of the urlFinPago property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUrlFinPago() {
        return urlFinPago;
    }

    /**
     * Sets the value of the urlFinPago property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUrlFinPago(String value) {
        this.urlFinPago = value;
    }

    /**
     * Gets the value of the vecesPagado property.
     * 
     */
    public int getVecesPagado() {
        return vecesPagado;
    }

    /**
     * Sets the value of the vecesPagado property.
     * 
     */
    public void setVecesPagado(int value) {
        this.vecesPagado = value;
    }

    /**
     * Gets the value of the version property.
     * 
     */
    public int getVersion() {
        return version;
    }

    /**
     * Sets the value of the version property.
     * 
     */
    public void setVersion(int value) {
        this.version = value;
    }

}
