//
// Generated By:JAX-WS RI IBM 2.1.6 in JDK 6 (JAXB RI IBM JAXB 2.1.10 in JDK 6)
//


package cl.metlife.hdp.botonpago.dawsclient;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for botonConvenio complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="botonConvenio">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="botonInstitucionesPago" type="{http://daws.botonpago.hdp.metlife.cl/}botonInstitucionesPago" minOccurs="0"/>
 *         &lt;element name="botonLineasDeNegocio" type="{http://daws.botonpago.hdp.metlife.cl/}botonLineasDeNegocio" minOccurs="0"/>
 *         &lt;element name="configPath" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="id" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="llave" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="logPath" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="mostrarCupon" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="nombreComercio" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="numeroConvenio" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="pagoEnPopUp" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="rutComercio" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="urlInicioPago" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "botonConvenio", namespace = "http://daws.botonpago.hdp.metlife.cl/", propOrder = {
    "botonInstitucionesPago",
    "botonLineasDeNegocio",
    "configPath",
    "id",
    "llave",
    "logPath",
    "mostrarCupon",
    "nombreComercio",
    "numeroConvenio",
    "pagoEnPopUp",
    "rutComercio",
    "urlInicioPago"
})
public class BotonConvenio {

    protected BotonInstitucionesPago botonInstitucionesPago;
    protected BotonLineasDeNegocio botonLineasDeNegocio;
    protected String configPath;
    protected int id;
    protected String llave;
    protected String logPath;
    protected String mostrarCupon;
    protected String nombreComercio;
    protected String numeroConvenio;
    protected String pagoEnPopUp;
    protected String rutComercio;
    protected String urlInicioPago;

    /**
     * Gets the value of the botonInstitucionesPago property.
     * 
     * @return
     *     possible object is
     *     {@link BotonInstitucionesPago }
     *     
     */
    public BotonInstitucionesPago getBotonInstitucionesPago() {
        return botonInstitucionesPago;
    }

    /**
     * Sets the value of the botonInstitucionesPago property.
     * 
     * @param value
     *     allowed object is
     *     {@link BotonInstitucionesPago }
     *     
     */
    public void setBotonInstitucionesPago(BotonInstitucionesPago value) {
        this.botonInstitucionesPago = value;
    }

    /**
     * Gets the value of the botonLineasDeNegocio property.
     * 
     * @return
     *     possible object is
     *     {@link BotonLineasDeNegocio }
     *     
     */
    public BotonLineasDeNegocio getBotonLineasDeNegocio() {
        return botonLineasDeNegocio;
    }

    /**
     * Sets the value of the botonLineasDeNegocio property.
     * 
     * @param value
     *     allowed object is
     *     {@link BotonLineasDeNegocio }
     *     
     */
    public void setBotonLineasDeNegocio(BotonLineasDeNegocio value) {
        this.botonLineasDeNegocio = value;
    }

    /**
     * Gets the value of the configPath property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getConfigPath() {
        return configPath;
    }

    /**
     * Sets the value of the configPath property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setConfigPath(String value) {
        this.configPath = value;
    }

    /**
     * Gets the value of the id property.
     * 
     */
    public int getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     */
    public void setId(int value) {
        this.id = value;
    }

    /**
     * Gets the value of the llave property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLlave() {
        return llave;
    }

    /**
     * Sets the value of the llave property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLlave(String value) {
        this.llave = value;
    }

    /**
     * Gets the value of the logPath property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLogPath() {
        return logPath;
    }

    /**
     * Sets the value of the logPath property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLogPath(String value) {
        this.logPath = value;
    }

    /**
     * Gets the value of the mostrarCupon property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMostrarCupon() {
        return mostrarCupon;
    }

    /**
     * Sets the value of the mostrarCupon property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMostrarCupon(String value) {
        this.mostrarCupon = value;
    }

    /**
     * Gets the value of the nombreComercio property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNombreComercio() {
        return nombreComercio;
    }

    /**
     * Sets the value of the nombreComercio property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNombreComercio(String value) {
        this.nombreComercio = value;
    }

    /**
     * Gets the value of the numeroConvenio property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNumeroConvenio() {
        return numeroConvenio;
    }

    /**
     * Sets the value of the numeroConvenio property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNumeroConvenio(String value) {
        this.numeroConvenio = value;
    }

    /**
     * Gets the value of the pagoEnPopUp property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPagoEnPopUp() {
        return pagoEnPopUp;
    }

    /**
     * Sets the value of the pagoEnPopUp property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPagoEnPopUp(String value) {
        this.pagoEnPopUp = value;
    }

    /**
     * Gets the value of the rutComercio property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRutComercio() {
        return rutComercio;
    }

    /**
     * Sets the value of the rutComercio property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRutComercio(String value) {
        this.rutComercio = value;
    }

    /**
     * Gets the value of the urlInicioPago property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUrlInicioPago() {
        return urlInicioPago;
    }

    /**
     * Sets the value of the urlInicioPago property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUrlInicioPago(String value) {
        this.urlInicioPago = value;
    }

}
