//
// Generated By:JAX-WS RI IBM 2.1.6 in JDK 6 (JAXB RI IBM JAXB 2.1.10 in JDK 6)
//


package cl.metlife.hdp.botonpago.dawsclient;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for configuracionesParser complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="configuracionesParser">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="idConfigParsers" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *         &lt;element name="institucionesDePago" type="{http://daws.botonpago.hdp.metlife.cl/}institucionesDePago" minOccurs="0"/>
 *         &lt;element name="nombreParametro" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="valorParametro" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "configuracionesParser", namespace = "http://daws.botonpago.hdp.metlife.cl/", propOrder = {
    "idConfigParsers",
    "institucionesDePago",
    "nombreParametro",
    "valorParametro"
})
public class ConfiguracionesParser {

    protected long idConfigParsers;
    protected InstitucionesDePago institucionesDePago;
    protected String nombreParametro;
    protected String valorParametro;

    /**
     * Gets the value of the idConfigParsers property.
     * 
     */
    public long getIdConfigParsers() {
        return idConfigParsers;
    }

    /**
     * Sets the value of the idConfigParsers property.
     * 
     */
    public void setIdConfigParsers(long value) {
        this.idConfigParsers = value;
    }

    /**
     * Gets the value of the institucionesDePago property.
     * 
     * @return
     *     possible object is
     *     {@link InstitucionesDePago }
     *     
     */
    public InstitucionesDePago getInstitucionesDePago() {
        return institucionesDePago;
    }

    /**
     * Sets the value of the institucionesDePago property.
     * 
     * @param value
     *     allowed object is
     *     {@link InstitucionesDePago }
     *     
     */
    public void setInstitucionesDePago(InstitucionesDePago value) {
        this.institucionesDePago = value;
    }

    /**
     * Gets the value of the nombreParametro property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNombreParametro() {
        return nombreParametro;
    }

    /**
     * Sets the value of the nombreParametro property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNombreParametro(String value) {
        this.nombreParametro = value;
    }

    /**
     * Gets the value of the valorParametro property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getValorParametro() {
        return valorParametro;
    }

    /**
     * Sets the value of the valorParametro property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setValorParametro(String value) {
        this.valorParametro = value;
    }

}
