//
// Generated By:JAX-WS RI IBM 2.1.6 in JDK 6 (JAXB RI IBM JAXB 2.1.10 in JDK 6)
//


package cl.metlife.hdp.botonpago.dawsclient;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for configuracionesApp complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="configuracionesApp">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="grupoConfig" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="idConfigApp" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="nombreParametroApp" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="tipo" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="valorParametroApp" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "configuracionesApp", namespace = "http://daws.botonpago.hdp.metlife.cl/", propOrder = {
    "grupoConfig",
    "idConfigApp",
    "nombreParametroApp",
    "tipo",
    "valorParametroApp"
})
public class ConfiguracionesApp {

    protected String grupoConfig;
    protected int idConfigApp;
    protected String nombreParametroApp;
    protected String tipo;
    protected String valorParametroApp;

    /**
     * Gets the value of the grupoConfig property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGrupoConfig() {
        return grupoConfig;
    }

    /**
     * Sets the value of the grupoConfig property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGrupoConfig(String value) {
        this.grupoConfig = value;
    }

    /**
     * Gets the value of the idConfigApp property.
     * 
     */
    public int getIdConfigApp() {
        return idConfigApp;
    }

    /**
     * Sets the value of the idConfigApp property.
     * 
     */
    public void setIdConfigApp(int value) {
        this.idConfigApp = value;
    }

    /**
     * Gets the value of the nombreParametroApp property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNombreParametroApp() {
        return nombreParametroApp;
    }

    /**
     * Sets the value of the nombreParametroApp property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNombreParametroApp(String value) {
        this.nombreParametroApp = value;
    }

    /**
     * Gets the value of the tipo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTipo() {
        return tipo;
    }

    /**
     * Sets the value of the tipo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTipo(String value) {
        this.tipo = value;
    }

    /**
     * Gets the value of the valorParametroApp property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getValorParametroApp() {
        return valorParametroApp;
    }

    /**
     * Sets the value of the valorParametroApp property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setValorParametroApp(String value) {
        this.valorParametroApp = value;
    }

}
