//
// Generated By:JAX-WS RI IBM 2.1.6 in JDK 6 (JAXB RI IBM JAXB 2.1.10 in JDK 6)
//


package cl.metlife.hdp.botonpago.dawsclient;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for getCampaignCSSResponse complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="getCampaignCSSResponse">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="CSS" type="{http://daws.botonpago.hdp.metlife.cl/}botonCampaign" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "getCampaignCSSResponse", namespace = "http://daws.botonpago.hdp.metlife.cl/", propOrder = {
    "css"
})
public class GetCampaignCSSResponse {

    @XmlElement(name = "CSS")
    protected BotonCampaign css;

    /**
     * Gets the value of the css property.
     * 
     * @return
     *     possible object is
     *     {@link BotonCampaign }
     *     
     */
    public BotonCampaign getCSS() {
        return css;
    }

    /**
     * Sets the value of the css property.
     * 
     * @param value
     *     allowed object is
     *     {@link BotonCampaign }
     *     
     */
    public void setCSS(BotonCampaign value) {
        this.css = value;
    }

}
