//
// Generated By:JAX-WS RI IBM 2.1.6 in JDK 6 (JAXB RI IBM JAXB 2.1.10 in JDK 6)
//


package cl.metlife.hdp.botonpago.dawsclient;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for institucionesDePago complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="institucionesDePago">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="archivosConciliacions" type="{http://daws.botonpago.hdp.metlife.cl/}archivosConciliacion" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="configuracionesParsers" type="{http://daws.botonpago.hdp.metlife.cl/}configuracionesParser" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="idInstitucionPago" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *         &lt;element name="logs" type="{http://daws.botonpago.hdp.metlife.cl/}log" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="nombreInstitucionPago" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="pagos" type="{http://daws.botonpago.hdp.metlife.cl/}pago" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="tipoDocumento" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="tipoParser" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "institucionesDePago", namespace = "http://daws.botonpago.hdp.metlife.cl/", propOrder = {
    "archivosConciliacions",
    "configuracionesParsers",
    "idInstitucionPago",
    "logs",
    "nombreInstitucionPago",
    "pagos",
    "tipoDocumento",
    "tipoParser"
})
public class InstitucionesDePago {

    @XmlElement(nillable = true)
    protected List<ArchivosConciliacion> archivosConciliacions;
    @XmlElement(nillable = true)
    protected List<ConfiguracionesParser> configuracionesParsers;
    protected long idInstitucionPago;
    @XmlElement(nillable = true)
    protected List<Log> logs;
    protected String nombreInstitucionPago;
    @XmlElement(nillable = true)
    protected List<Pago> pagos;
    protected String tipoDocumento;
    protected String tipoParser;

    /**
     * Gets the value of the archivosConciliacions property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the archivosConciliacions property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getArchivosConciliacions().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ArchivosConciliacion }
     * 
     * 
     */
    public List<ArchivosConciliacion> getArchivosConciliacions() {
        if (archivosConciliacions == null) {
            archivosConciliacions = new ArrayList<ArchivosConciliacion>();
        }
        return this.archivosConciliacions;
    }

    /**
     * Gets the value of the configuracionesParsers property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the configuracionesParsers property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getConfiguracionesParsers().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ConfiguracionesParser }
     * 
     * 
     */
    public List<ConfiguracionesParser> getConfiguracionesParsers() {
        if (configuracionesParsers == null) {
            configuracionesParsers = new ArrayList<ConfiguracionesParser>();
        }
        return this.configuracionesParsers;
    }

    /**
     * Gets the value of the idInstitucionPago property.
     * 
     */
    public long getIdInstitucionPago() {
        return idInstitucionPago;
    }

    /**
     * Sets the value of the idInstitucionPago property.
     * 
     */
    public void setIdInstitucionPago(long value) {
        this.idInstitucionPago = value;
    }

    /**
     * Gets the value of the logs property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the logs property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getLogs().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Log }
     * 
     * 
     */
    public List<Log> getLogs() {
        if (logs == null) {
            logs = new ArrayList<Log>();
        }
        return this.logs;
    }

    /**
     * Gets the value of the nombreInstitucionPago property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNombreInstitucionPago() {
        return nombreInstitucionPago;
    }

    /**
     * Sets the value of the nombreInstitucionPago property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNombreInstitucionPago(String value) {
        this.nombreInstitucionPago = value;
    }

    /**
     * Gets the value of the pagos property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the pagos property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPagos().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Pago }
     * 
     * 
     */
    public List<Pago> getPagos() {
        if (pagos == null) {
            pagos = new ArrayList<Pago>();
        }
        return this.pagos;
    }

    /**
     * Gets the value of the tipoDocumento property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTipoDocumento() {
        return tipoDocumento;
    }

    /**
     * Sets the value of the tipoDocumento property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTipoDocumento(String value) {
        this.tipoDocumento = value;
    }

    /**
     * Gets the value of the tipoParser property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTipoParser() {
        return tipoParser;
    }

    /**
     * Sets the value of the tipoParser property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTipoParser(String value) {
        this.tipoParser = value;
    }

}
