//
// Generated By:JAX-WS RI IBM 2.1.6 in JDK 6 (JAXB RI IBM JAXB 2.1.10 in JDK 6)
//


package cl.metlife.hdp.botonpago.dawsclient;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for lineasDeNegocio complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="lineasDeNegocio">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="descripcion" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="idLineaNegocio" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *         &lt;element name="identificadorCupon" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="institucion" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="logs" type="{http://daws.botonpago.hdp.metlife.cl/}log" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="nombreLineaNegocio" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="pagos" type="{http://daws.botonpago.hdp.metlife.cl/}pago" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="urlConciliador" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "lineasDeNegocio", namespace = "http://daws.botonpago.hdp.metlife.cl/", propOrder = {
    "descripcion",
    "idLineaNegocio",
    "identificadorCupon",
    "institucion",
    "logs",
    "nombreLineaNegocio",
    "pagos",
    "urlConciliador"
})
public class LineasDeNegocio {

    protected String descripcion;
    protected long idLineaNegocio;
    protected String identificadorCupon;
    protected String institucion;
    @XmlElement(nillable = true)
    protected List<Log> logs;
    protected String nombreLineaNegocio;
    @XmlElement(nillable = true)
    protected List<Pago> pagos;
    protected String urlConciliador;

    /**
     * Gets the value of the descripcion property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDescripcion() {
        return descripcion;
    }

    /**
     * Sets the value of the descripcion property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDescripcion(String value) {
        this.descripcion = value;
    }

    /**
     * Gets the value of the idLineaNegocio property.
     * 
     */
    public long getIdLineaNegocio() {
        return idLineaNegocio;
    }

    /**
     * Sets the value of the idLineaNegocio property.
     * 
     */
    public void setIdLineaNegocio(long value) {
        this.idLineaNegocio = value;
    }

    /**
     * Gets the value of the identificadorCupon property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIdentificadorCupon() {
        return identificadorCupon;
    }

    /**
     * Sets the value of the identificadorCupon property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIdentificadorCupon(String value) {
        this.identificadorCupon = value;
    }

    /**
     * Gets the value of the institucion property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInstitucion() {
        return institucion;
    }

    /**
     * Sets the value of the institucion property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInstitucion(String value) {
        this.institucion = value;
    }

    /**
     * Gets the value of the logs property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the logs property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getLogs().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Log }
     * 
     * 
     */
    public List<Log> getLogs() {
        if (logs == null) {
            logs = new ArrayList<Log>();
        }
        return this.logs;
    }

    /**
     * Gets the value of the nombreLineaNegocio property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNombreLineaNegocio() {
        return nombreLineaNegocio;
    }

    /**
     * Sets the value of the nombreLineaNegocio property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNombreLineaNegocio(String value) {
        this.nombreLineaNegocio = value;
    }

    /**
     * Gets the value of the pagos property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the pagos property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPagos().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Pago }
     * 
     * 
     */
    public List<Pago> getPagos() {
        if (pagos == null) {
            pagos = new ArrayList<Pago>();
        }
        return this.pagos;
    }

    /**
     * Gets the value of the urlConciliador property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUrlConciliador() {
        return urlConciliador;
    }

    /**
     * Sets the value of the urlConciliador property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUrlConciliador(String value) {
        this.urlConciliador = value;
    }

}
