//
// Generated By:JAX-WS RI IBM 2.1.6 in JDK 6 (JAXB RI IBM JAXB 2.1.10 in JDK 6)
//


package cl.metlife.hdp.botonpago.dawsclient;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for log complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="log">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="archivosConciliacion" type="{http://daws.botonpago.hdp.metlife.cl/}archivosConciliacion" minOccurs="0"/>
 *         &lt;element name="cliente" type="{http://daws.botonpago.hdp.metlife.cl/}cliente" minOccurs="0"/>
 *         &lt;element name="descripcion" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="estadoAnterior" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="estadoNuevo" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="fecha" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
 *         &lt;element name="idLog" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *         &lt;element name="institucionesDePago" type="{http://daws.botonpago.hdp.metlife.cl/}institucionesDePago" minOccurs="0"/>
 *         &lt;element name="lineasDeNegocio" type="{http://daws.botonpago.hdp.metlife.cl/}lineasDeNegocio" minOccurs="0"/>
 *         &lt;element name="nivel" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="nombreAplicacion" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="pago" type="{http://daws.botonpago.hdp.metlife.cl/}pago" minOccurs="0"/>
 *         &lt;element name="resumenDescripcion" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="TProceso" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="usuario" type="{http://daws.botonpago.hdp.metlife.cl/}usuario" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "log", namespace = "http://daws.botonpago.hdp.metlife.cl/", propOrder = {
    "archivosConciliacion",
    "cliente",
    "descripcion",
    "estadoAnterior",
    "estadoNuevo",
    "fecha",
    "idLog",
    "institucionesDePago",
    "lineasDeNegocio",
    "nivel",
    "nombreAplicacion",
    "pago",
    "resumenDescripcion",
    "tProceso",
    "usuario"
})
public class Log {

    protected ArchivosConciliacion archivosConciliacion;
    protected Cliente cliente;
    protected String descripcion;
    protected String estadoAnterior;
    protected String estadoNuevo;
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar fecha;
    protected long idLog;
    protected InstitucionesDePago institucionesDePago;
    protected LineasDeNegocio lineasDeNegocio;
    protected String nivel;
    protected String nombreAplicacion;
    protected Pago pago;
    protected String resumenDescripcion;
    @XmlElement(name = "TProceso")
    protected Integer tProceso;
    protected Usuario usuario;

    /**
     * Gets the value of the archivosConciliacion property.
     * 
     * @return
     *     possible object is
     *     {@link ArchivosConciliacion }
     *     
     */
    public ArchivosConciliacion getArchivosConciliacion() {
        return archivosConciliacion;
    }

    /**
     * Sets the value of the archivosConciliacion property.
     * 
     * @param value
     *     allowed object is
     *     {@link ArchivosConciliacion }
     *     
     */
    public void setArchivosConciliacion(ArchivosConciliacion value) {
        this.archivosConciliacion = value;
    }

    /**
     * Gets the value of the cliente property.
     * 
     * @return
     *     possible object is
     *     {@link Cliente }
     *     
     */
    public Cliente getCliente() {
        return cliente;
    }

    /**
     * Sets the value of the cliente property.
     * 
     * @param value
     *     allowed object is
     *     {@link Cliente }
     *     
     */
    public void setCliente(Cliente value) {
        this.cliente = value;
    }

    /**
     * Gets the value of the descripcion property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDescripcion() {
        return descripcion;
    }

    /**
     * Sets the value of the descripcion property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDescripcion(String value) {
        this.descripcion = value;
    }

    /**
     * Gets the value of the estadoAnterior property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEstadoAnterior() {
        return estadoAnterior;
    }

    /**
     * Sets the value of the estadoAnterior property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEstadoAnterior(String value) {
        this.estadoAnterior = value;
    }

    /**
     * Gets the value of the estadoNuevo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEstadoNuevo() {
        return estadoNuevo;
    }

    /**
     * Sets the value of the estadoNuevo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEstadoNuevo(String value) {
        this.estadoNuevo = value;
    }

    /**
     * Gets the value of the fecha property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getFecha() {
        return fecha;
    }

    /**
     * Sets the value of the fecha property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setFecha(XMLGregorianCalendar value) {
        this.fecha = value;
    }

    /**
     * Gets the value of the idLog property.
     * 
     */
    public long getIdLog() {
        return idLog;
    }

    /**
     * Sets the value of the idLog property.
     * 
     */
    public void setIdLog(long value) {
        this.idLog = value;
    }

    /**
     * Gets the value of the institucionesDePago property.
     * 
     * @return
     *     possible object is
     *     {@link InstitucionesDePago }
     *     
     */
    public InstitucionesDePago getInstitucionesDePago() {
        return institucionesDePago;
    }

    /**
     * Sets the value of the institucionesDePago property.
     * 
     * @param value
     *     allowed object is
     *     {@link InstitucionesDePago }
     *     
     */
    public void setInstitucionesDePago(InstitucionesDePago value) {
        this.institucionesDePago = value;
    }

    /**
     * Gets the value of the lineasDeNegocio property.
     * 
     * @return
     *     possible object is
     *     {@link LineasDeNegocio }
     *     
     */
    public LineasDeNegocio getLineasDeNegocio() {
        return lineasDeNegocio;
    }

    /**
     * Sets the value of the lineasDeNegocio property.
     * 
     * @param value
     *     allowed object is
     *     {@link LineasDeNegocio }
     *     
     */
    public void setLineasDeNegocio(LineasDeNegocio value) {
        this.lineasDeNegocio = value;
    }

    /**
     * Gets the value of the nivel property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNivel() {
        return nivel;
    }

    /**
     * Sets the value of the nivel property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNivel(String value) {
        this.nivel = value;
    }

    /**
     * Gets the value of the nombreAplicacion property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNombreAplicacion() {
        return nombreAplicacion;
    }

    /**
     * Sets the value of the nombreAplicacion property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNombreAplicacion(String value) {
        this.nombreAplicacion = value;
    }

    /**
     * Gets the value of the pago property.
     * 
     * @return
     *     possible object is
     *     {@link Pago }
     *     
     */
    public Pago getPago() {
        return pago;
    }

    /**
     * Sets the value of the pago property.
     * 
     * @param value
     *     allowed object is
     *     {@link Pago }
     *     
     */
    public void setPago(Pago value) {
        this.pago = value;
    }

    /**
     * Gets the value of the resumenDescripcion property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getResumenDescripcion() {
        return resumenDescripcion;
    }

    /**
     * Sets the value of the resumenDescripcion property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setResumenDescripcion(String value) {
        this.resumenDescripcion = value;
    }

    /**
     * Gets the value of the tProceso property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getTProceso() {
        return tProceso;
    }

    /**
     * Sets the value of the tProceso property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setTProceso(Integer value) {
        this.tProceso = value;
    }

    /**
     * Gets the value of the usuario property.
     * 
     * @return
     *     possible object is
     *     {@link Usuario }
     *     
     */
    public Usuario getUsuario() {
        return usuario;
    }

    /**
     * Sets the value of the usuario property.
     * 
     * @param value
     *     allowed object is
     *     {@link Usuario }
     *     
     */
    public void setUsuario(Usuario value) {
        this.usuario = value;
    }

}
