//
// Generated By:JAX-WS RI IBM 2.1.6 in JDK 6 (JAXB RI IBM JAXB 2.1.10 in JDK 6)
//


package cl.metlife.hdp.botonpago.dawsclient;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for markAsPayedBotonPago complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="markAsPayedBotonPago">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="BotonPagoInfo" type="{http://daws.botonpago.hdp.metlife.cl/}botonPago" minOccurs="0"/>
 *         &lt;element name="idConvenio" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="notifyMessage" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="clientIP" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "markAsPayedBotonPago", namespace = "http://daws.botonpago.hdp.metlife.cl/", propOrder = {
    "botonPagoInfo",
    "idConvenio",
    "notifyMessage",
    "clientIP"
})
public class MarkAsPayedBotonPago {

    @XmlElement(name = "BotonPagoInfo")
    protected BotonPago botonPagoInfo;
    protected int idConvenio;
    protected String notifyMessage;
    protected String clientIP;

    /**
     * Gets the value of the botonPagoInfo property.
     * 
     * @return
     *     possible object is
     *     {@link BotonPago }
     *     
     */
    public BotonPago getBotonPagoInfo() {
        return botonPagoInfo;
    }

    /**
     * Sets the value of the botonPagoInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link BotonPago }
     *     
     */
    public void setBotonPagoInfo(BotonPago value) {
        this.botonPagoInfo = value;
    }

    /**
     * Gets the value of the idConvenio property.
     * 
     */
    public int getIdConvenio() {
        return idConvenio;
    }

    /**
     * Sets the value of the idConvenio property.
     * 
     */
    public void setIdConvenio(int value) {
        this.idConvenio = value;
    }

    /**
     * Gets the value of the notifyMessage property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNotifyMessage() {
        return notifyMessage;
    }

    /**
     * Sets the value of the notifyMessage property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNotifyMessage(String value) {
        this.notifyMessage = value;
    }

    /**
     * Gets the value of the clientIP property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getClientIP() {
        return clientIP;
    }

    /**
     * Sets the value of the clientIP property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setClientIP(String value) {
        this.clientIP = value;
    }

}
