//
// Generated By:JAX-WS RI IBM 2.1.6 in JDK 6 (JAXB RI IBM JAXB 2.1.10 in JDK 6)
//


package cl.metlife.hdp.botonpago.dawsclient;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the catalina.servlets.test package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _MarkAsPayedBotonPagoResponse_QNAME = new QName("http://daws.botonpago.hdp.metlife.cl/", "markAsPayedBotonPagoResponse");
    private final static QName _AddPaymentInfoToInvoice_QNAME = new QName("http://daws.botonpago.hdp.metlife.cl/", "addPaymentInfoToInvoice");
    private final static QName _IsPayed_QNAME = new QName("http://daws.botonpago.hdp.metlife.cl/", "isPayed");
    private final static QName _LoadConfigResponse_QNAME = new QName("http://daws.botonpago.hdp.metlife.cl/", "loadConfigResponse");
    private final static QName _GetPagoResponse_QNAME = new QName("http://daws.botonpago.hdp.metlife.cl/", "getPagoResponse");
    private final static QName _SetAgreementToPayment_QNAME = new QName("http://daws.botonpago.hdp.metlife.cl/", "setAgreementToPayment");
    private final static QName _MarkAsPayedBotonPago_QNAME = new QName("http://daws.botonpago.hdp.metlife.cl/", "markAsPayedBotonPago");
    private final static QName _LoadConfig_QNAME = new QName("http://daws.botonpago.hdp.metlife.cl/", "loadConfig");
    private final static QName _GetPago_QNAME = new QName("http://daws.botonpago.hdp.metlife.cl/", "getPago");
    private final static QName _SetAgreementToPaymentResponse_QNAME = new QName("http://daws.botonpago.hdp.metlife.cl/", "setAgreementToPaymentResponse");
    private final static QName _GetCampaignCSS_QNAME = new QName("http://daws.botonpago.hdp.metlife.cl/", "getCampaignCSS");
    private final static QName _MarkAsRejectedResponse_QNAME = new QName("http://daws.botonpago.hdp.metlife.cl/", "markAsRejectedResponse");
    private final static QName _AddPaymentInfoToInvoiceResponse_QNAME = new QName("http://daws.botonpago.hdp.metlife.cl/", "addPaymentInfoToInvoiceResponse");
    private final static QName _GetCampaignCSSResponse_QNAME = new QName("http://daws.botonpago.hdp.metlife.cl/", "getCampaignCSSResponse");
    private final static QName _MarkAsPayedResponse_QNAME = new QName("http://daws.botonpago.hdp.metlife.cl/", "markAsPayedResponse");
    private final static QName _IsPayedResponse_QNAME = new QName("http://daws.botonpago.hdp.metlife.cl/", "isPayedResponse");
    private final static QName _MarkAsPayed_QNAME = new QName("http://daws.botonpago.hdp.metlife.cl/", "markAsPayed");
    private final static QName _MarkAsRejected_QNAME = new QName("http://daws.botonpago.hdp.metlife.cl/", "markAsRejected");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: catalina.servlets.test
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link LineasDeNegocio }
     * 
     */
    public LineasDeNegocio createLineasDeNegocio() {
        return new LineasDeNegocio();
    }

    /**
     * Create an instance of {@link BotonBoleta }
     * 
     */
    public BotonBoleta createBotonBoleta() {
        return new BotonBoleta();
    }

    /**
     * Create an instance of {@link BotonEstado }
     * 
     */
    public BotonEstado createBotonEstado() {
        return new BotonEstado();
    }

    /**
     * Create an instance of {@link InstitucionesDePago }
     * 
     */
    public InstitucionesDePago createInstitucionesDePago() {
        return new InstitucionesDePago();
    }

    /**
     * Create an instance of {@link IsPayed }
     * 
     */
    public IsPayed createIsPayed() {
        return new IsPayed();
    }

    /**
     * Create an instance of {@link BotonLineasDeNegocio }
     * 
     */
    public BotonLineasDeNegocio createBotonLineasDeNegocio() {
        return new BotonLineasDeNegocio();
    }

    /**
     * Create an instance of {@link ConfiguracionesApp }
     * 
     */
    public ConfiguracionesApp createConfiguracionesApp() {
        return new ConfiguracionesApp();
    }

    /**
     * Create an instance of {@link Estado }
     * 
     */
    public Estado createEstado() {
        return new Estado();
    }

    /**
     * Create an instance of {@link LoadConfig }
     * 
     */
    public LoadConfig createLoadConfig() {
        return new LoadConfig();
    }

    /**
     * Create an instance of {@link BotonConvenio }
     * 
     */
    public BotonConvenio createBotonConvenio() {
        return new BotonConvenio();
    }

    /**
     * Create an instance of {@link CodigosMoneda }
     * 
     */
    public CodigosMoneda createCodigosMoneda() {
        return new CodigosMoneda();
    }

    /**
     * Create an instance of {@link IsPayedResponse }
     * 
     */
    public IsPayedResponse createIsPayedResponse() {
        return new IsPayedResponse();
    }

    /**
     * Create an instance of {@link Log }
     * 
     */
    public Log createLog() {
        return new Log();
    }

    /**
     * Create an instance of {@link BotonAcceso }
     * 
     */
    public BotonAcceso createBotonAcceso() {
        return new BotonAcceso();
    }

    /**
     * Create an instance of {@link GetCampaignCSS }
     * 
     */
    public GetCampaignCSS createGetCampaignCSS() {
        return new GetCampaignCSS();
    }

    /**
     * Create an instance of {@link MarkAsPayedBotonPago }
     * 
     */
    public MarkAsPayedBotonPago createMarkAsPayedBotonPago() {
        return new MarkAsPayedBotonPago();
    }

    /**
     * Create an instance of {@link PaymentInfo }
     * 
     */
    public PaymentInfo createPaymentInfo() {
        return new PaymentInfo();
    }

    /**
     * Create an instance of {@link MarkAsRejectedResponse }
     * 
     */
    public MarkAsRejectedResponse createMarkAsRejectedResponse() {
        return new MarkAsRejectedResponse();
    }

    /**
     * Create an instance of {@link GetCampaignCSSResponse }
     * 
     */
    public GetCampaignCSSResponse createGetCampaignCSSResponse() {
        return new GetCampaignCSSResponse();
    }

    /**
     * Create an instance of {@link Cliente }
     * 
     */
    public Cliente createCliente() {
        return new Cliente();
    }

    /**
     * Create an instance of {@link ConfiguracionesParser }
     * 
     */
    public ConfiguracionesParser createConfiguracionesParser() {
        return new ConfiguracionesParser();
    }

    /**
     * Create an instance of {@link Pago }
     * 
     */
    public Pago createPago() {
        return new Pago();
    }

    /**
     * Create an instance of {@link Usuario }
     * 
     */
    public Usuario createUsuario() {
        return new Usuario();
    }

    /**
     * Create an instance of {@link BotonInstitucionesPago }
     * 
     */
    public BotonInstitucionesPago createBotonInstitucionesPago() {
        return new BotonInstitucionesPago();
    }

    /**
     * Create an instance of {@link ArchivosConciliacion }
     * 
     */
    public ArchivosConciliacion createArchivosConciliacion() {
        return new ArchivosConciliacion();
    }

    /**
     * Create an instance of {@link AddPaymentInfoToInvoice }
     * 
     */
    public AddPaymentInfoToInvoice createAddPaymentInfoToInvoice() {
        return new AddPaymentInfoToInvoice();
    }

    /**
     * Create an instance of {@link AddPaymentInfoToInvoiceResponse }
     * 
     */
    public AddPaymentInfoToInvoiceResponse createAddPaymentInfoToInvoiceResponse() {
        return new AddPaymentInfoToInvoiceResponse();
    }

    /**
     * Create an instance of {@link BotonInstitucionesPagoXml }
     * 
     */
    public BotonInstitucionesPagoXml createBotonInstitucionesPagoXml() {
        return new BotonInstitucionesPagoXml();
    }

    /**
     * Create an instance of {@link MarkAsRejected }
     * 
     */
    public MarkAsRejected createMarkAsRejected() {
        return new MarkAsRejected();
    }

    /**
     * Create an instance of {@link MarkAsPayedResponse }
     * 
     */
    public MarkAsPayedResponse createMarkAsPayedResponse() {
        return new MarkAsPayedResponse();
    }

    /**
     * Create an instance of {@link LoadConfigResponse }
     * 
     */
    public LoadConfigResponse createLoadConfigResponse() {
        return new LoadConfigResponse();
    }

    /**
     * Create an instance of {@link SetAgreementToPayment }
     * 
     */
    public SetAgreementToPayment createSetAgreementToPayment() {
        return new SetAgreementToPayment();
    }

    /**
     * Create an instance of {@link GetPago }
     * 
     */
    public GetPago createGetPago() {
        return new GetPago();
    }

    /**
     * Create an instance of {@link MarkAsPayed }
     * 
     */
    public MarkAsPayed createMarkAsPayed() {
        return new MarkAsPayed();
    }

    /**
     * Create an instance of {@link GetPagoResponse }
     * 
     */
    public GetPagoResponse createGetPagoResponse() {
        return new GetPagoResponse();
    }

    /**
     * Create an instance of {@link MarkAsPayedBotonPagoResponse }
     * 
     */
    public MarkAsPayedBotonPagoResponse createMarkAsPayedBotonPagoResponse() {
        return new MarkAsPayedBotonPagoResponse();
    }

    /**
     * Create an instance of {@link BotonCampaign }
     * 
     */
    public BotonCampaign createBotonCampaign() {
        return new BotonCampaign();
    }

    /**
     * Create an instance of {@link BotonPago }
     * 
     */
    public BotonPago createBotonPago() {
        return new BotonPago();
    }

    /**
     * Create an instance of {@link SetAgreementToPaymentResponse }
     * 
     */
    public SetAgreementToPaymentResponse createSetAgreementToPaymentResponse() {
        return new SetAgreementToPaymentResponse();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link MarkAsPayedBotonPagoResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://daws.botonpago.hdp.metlife.cl/", name = "markAsPayedBotonPagoResponse")
    public JAXBElement<MarkAsPayedBotonPagoResponse> createMarkAsPayedBotonPagoResponse(MarkAsPayedBotonPagoResponse value) {
        return new JAXBElement<MarkAsPayedBotonPagoResponse>(_MarkAsPayedBotonPagoResponse_QNAME, MarkAsPayedBotonPagoResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AddPaymentInfoToInvoice }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://daws.botonpago.hdp.metlife.cl/", name = "addPaymentInfoToInvoice")
    public JAXBElement<AddPaymentInfoToInvoice> createAddPaymentInfoToInvoice(AddPaymentInfoToInvoice value) {
        return new JAXBElement<AddPaymentInfoToInvoice>(_AddPaymentInfoToInvoice_QNAME, AddPaymentInfoToInvoice.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link IsPayed }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://daws.botonpago.hdp.metlife.cl/", name = "isPayed")
    public JAXBElement<IsPayed> createIsPayed(IsPayed value) {
        return new JAXBElement<IsPayed>(_IsPayed_QNAME, IsPayed.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link LoadConfigResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://daws.botonpago.hdp.metlife.cl/", name = "loadConfigResponse")
    public JAXBElement<LoadConfigResponse> createLoadConfigResponse(LoadConfigResponse value) {
        return new JAXBElement<LoadConfigResponse>(_LoadConfigResponse_QNAME, LoadConfigResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetPagoResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://daws.botonpago.hdp.metlife.cl/", name = "getPagoResponse")
    public JAXBElement<GetPagoResponse> createGetPagoResponse(GetPagoResponse value) {
        return new JAXBElement<GetPagoResponse>(_GetPagoResponse_QNAME, GetPagoResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SetAgreementToPayment }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://daws.botonpago.hdp.metlife.cl/", name = "setAgreementToPayment")
    public JAXBElement<SetAgreementToPayment> createSetAgreementToPayment(SetAgreementToPayment value) {
        return new JAXBElement<SetAgreementToPayment>(_SetAgreementToPayment_QNAME, SetAgreementToPayment.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link MarkAsPayedBotonPago }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://daws.botonpago.hdp.metlife.cl/", name = "markAsPayedBotonPago")
    public JAXBElement<MarkAsPayedBotonPago> createMarkAsPayedBotonPago(MarkAsPayedBotonPago value) {
        return new JAXBElement<MarkAsPayedBotonPago>(_MarkAsPayedBotonPago_QNAME, MarkAsPayedBotonPago.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link LoadConfig }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://daws.botonpago.hdp.metlife.cl/", name = "loadConfig")
    public JAXBElement<LoadConfig> createLoadConfig(LoadConfig value) {
        return new JAXBElement<LoadConfig>(_LoadConfig_QNAME, LoadConfig.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetPago }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://daws.botonpago.hdp.metlife.cl/", name = "getPago")
    public JAXBElement<GetPago> createGetPago(GetPago value) {
        return new JAXBElement<GetPago>(_GetPago_QNAME, GetPago.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SetAgreementToPaymentResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://daws.botonpago.hdp.metlife.cl/", name = "setAgreementToPaymentResponse")
    public JAXBElement<SetAgreementToPaymentResponse> createSetAgreementToPaymentResponse(SetAgreementToPaymentResponse value) {
        return new JAXBElement<SetAgreementToPaymentResponse>(_SetAgreementToPaymentResponse_QNAME, SetAgreementToPaymentResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetCampaignCSS }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://daws.botonpago.hdp.metlife.cl/", name = "getCampaignCSS")
    public JAXBElement<GetCampaignCSS> createGetCampaignCSS(GetCampaignCSS value) {
        return new JAXBElement<GetCampaignCSS>(_GetCampaignCSS_QNAME, GetCampaignCSS.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link MarkAsRejectedResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://daws.botonpago.hdp.metlife.cl/", name = "markAsRejectedResponse")
    public JAXBElement<MarkAsRejectedResponse> createMarkAsRejectedResponse(MarkAsRejectedResponse value) {
        return new JAXBElement<MarkAsRejectedResponse>(_MarkAsRejectedResponse_QNAME, MarkAsRejectedResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AddPaymentInfoToInvoiceResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://daws.botonpago.hdp.metlife.cl/", name = "addPaymentInfoToInvoiceResponse")
    public JAXBElement<AddPaymentInfoToInvoiceResponse> createAddPaymentInfoToInvoiceResponse(AddPaymentInfoToInvoiceResponse value) {
        return new JAXBElement<AddPaymentInfoToInvoiceResponse>(_AddPaymentInfoToInvoiceResponse_QNAME, AddPaymentInfoToInvoiceResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetCampaignCSSResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://daws.botonpago.hdp.metlife.cl/", name = "getCampaignCSSResponse")
    public JAXBElement<GetCampaignCSSResponse> createGetCampaignCSSResponse(GetCampaignCSSResponse value) {
        return new JAXBElement<GetCampaignCSSResponse>(_GetCampaignCSSResponse_QNAME, GetCampaignCSSResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link MarkAsPayedResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://daws.botonpago.hdp.metlife.cl/", name = "markAsPayedResponse")
    public JAXBElement<MarkAsPayedResponse> createMarkAsPayedResponse(MarkAsPayedResponse value) {
        return new JAXBElement<MarkAsPayedResponse>(_MarkAsPayedResponse_QNAME, MarkAsPayedResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link IsPayedResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://daws.botonpago.hdp.metlife.cl/", name = "isPayedResponse")
    public JAXBElement<IsPayedResponse> createIsPayedResponse(IsPayedResponse value) {
        return new JAXBElement<IsPayedResponse>(_IsPayedResponse_QNAME, IsPayedResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link MarkAsPayed }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://daws.botonpago.hdp.metlife.cl/", name = "markAsPayed")
    public JAXBElement<MarkAsPayed> createMarkAsPayed(MarkAsPayed value) {
        return new JAXBElement<MarkAsPayed>(_MarkAsPayed_QNAME, MarkAsPayed.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link MarkAsRejected }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://daws.botonpago.hdp.metlife.cl/", name = "markAsRejected")
    public JAXBElement<MarkAsRejected> createMarkAsRejected(MarkAsRejected value) {
        return new JAXBElement<MarkAsRejected>(_MarkAsRejected_QNAME, MarkAsRejected.class, null, value);
    }

}
