//
// Generated By:JAX-WS RI IBM 2.1.6 in JDK 6 (JAXB RI IBM JAXB 2.1.10 in JDK 6)
//


package cl.metlife.hdp.botonpago.dawsclient;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;

@WebServiceClient(name = "PagoDAWS", targetNamespace = "http://daws.botonpago.hdp.metlife.cl/", wsdlLocation = "http://mlfsoaqat01:9080/BotonDePagoIntranet/PagoDAWS/PagoDAWS.wsdl")
public class PagoDAWS_Service
    extends Service
{

    private final static URL PAGODAWS_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(cl.metlife.hdp.botonpago.dawsclient.PagoDAWS_Service.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = cl.metlife.hdp.botonpago.dawsclient.PagoDAWS_Service.class.getResource(".");
            url = new URL(baseUrl, "http://mlfsoaqat01:9080/BotonDePagoIntranet/PagoDAWS/PagoDAWS.wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'http://mlfsoaqat01:9080/BotonDePagoIntranet/PagoDAWS/PagoDAWS.wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        PAGODAWS_WSDL_LOCATION = url;
    }

    public PagoDAWS_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public PagoDAWS_Service() {
        super(PAGODAWS_WSDL_LOCATION, new QName("http://daws.botonpago.hdp.metlife.cl/", "PagoDAWS"));
    }

    /**
     * 
     * @return
     *     returns PagoDAWS
     */
    @WebEndpoint(name = "PagoDAWS")
    public PagoDAWS getPagoDAWS() {
        return super.getPort(new QName("http://daws.botonpago.hdp.metlife.cl/", "PagoDAWS"), PagoDAWS.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns PagoDAWS
     */
    @WebEndpoint(name = "PagoDAWS")
    public PagoDAWS getPagoDAWS(WebServiceFeature... features) {
        return super.getPort(new QName("http://daws.botonpago.hdp.metlife.cl/", "PagoDAWS"), PagoDAWS.class, features);
    }

}
