//
// Generated By:JAX-WS RI IBM 2.1.6 in JDK 6 (JAXB RI IBM JAXB 2.1.10 in JDK 6)
//


package cl.metlife.hdp.botonpago.dawsclient;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

@WebService(name = "PagoDAWS", targetNamespace = "http://daws.botonpago.hdp.metlife.cl/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface PagoDAWS {


    /**
     * 
     * @param clientIP
     * @param idPago
     * @return
     *     returns catalina.servlets.test.PaymentInfo
     */
    @WebMethod(action = "getPago")
    @WebResult(name = "BotonPago", targetNamespace = "")
    @RequestWrapper(localName = "getPago", targetNamespace = "http://daws.botonpago.hdp.metlife.cl/", className = "catalina.servlets.test.GetPago")
    @ResponseWrapper(localName = "getPagoResponse", targetNamespace = "http://daws.botonpago.hdp.metlife.cl/", className = "catalina.servlets.test.GetPagoResponse")
    public PaymentInfo getPago(
            @WebParam(name = "idPago", targetNamespace = "")
                    int idPago,
            @WebParam(name = "clientIP", targetNamespace = "")
                    String clientIP);

    /**
     * 
     * @param clientIP
     * @param idPago
     * @param codigoTransaccion
     * @param codigoAutorizacion
     * @param notifyMessage
     * @param idConvenio
     * @return
     *     returns catalina.servlets.test.BotonPago
     */
    @WebMethod(action = "markAsPayed")
    @WebResult(name = "BotonPago", targetNamespace = "")
    @RequestWrapper(localName = "markAsPayed", targetNamespace = "http://daws.botonpago.hdp.metlife.cl/", className = "catalina.servlets.test.MarkAsPayed")
    @ResponseWrapper(localName = "markAsPayedResponse", targetNamespace = "http://daws.botonpago.hdp.metlife.cl/", className = "catalina.servlets.test.MarkAsPayedResponse")
    public BotonPago markAsPayed(
            @WebParam(name = "idPago", targetNamespace = "")
                    int idPago,
            @WebParam(name = "codigoTransaccion", targetNamespace = "")
                    String codigoTransaccion,
            @WebParam(name = "codigoAutorizacion", targetNamespace = "")
                    String codigoAutorizacion,
            @WebParam(name = "idConvenio", targetNamespace = "")
                    int idConvenio,
            @WebParam(name = "notifyMessage", targetNamespace = "")
                    String notifyMessage,
            @WebParam(name = "clientIP", targetNamespace = "")
                    String clientIP);

    /**
     * 
     * @param clientIP
     * @param botonPagoInfo
     * @param notifyMessage
     * @param idConvenio
     * @return
     *     returns catalina.servlets.test.BotonPago
     */
    @WebMethod(action = "markAsPayedBotonPago")
    @WebResult(name = "BotonPago", targetNamespace = "")
    @RequestWrapper(localName = "markAsPayedBotonPago", targetNamespace = "http://daws.botonpago.hdp.metlife.cl/", className = "catalina.servlets.test.MarkAsPayedBotonPago")
    @ResponseWrapper(localName = "markAsPayedBotonPagoResponse", targetNamespace = "http://daws.botonpago.hdp.metlife.cl/", className = "catalina.servlets.test.MarkAsPayedBotonPagoResponse")
    public BotonPago markAsPayedBotonPago(
            @WebParam(name = "BotonPagoInfo", targetNamespace = "")
                    BotonPago botonPagoInfo,
            @WebParam(name = "idConvenio", targetNamespace = "")
                    int idConvenio,
            @WebParam(name = "notifyMessage", targetNamespace = "")
                    String notifyMessage,
            @WebParam(name = "clientIP", targetNamespace = "")
                    String clientIP);

    /**
     * 
     * @param clientIP
     * @param reason
     * @param idPago
     * @param notifyMessage
     * @param idConvenio
     * @return
     *     returns catalina.servlets.test.BotonPago
     */
    @WebMethod(action = "markAsRejected")
    @WebResult(name = "BotonPago", targetNamespace = "")
    @RequestWrapper(localName = "markAsRejected", targetNamespace = "http://daws.botonpago.hdp.metlife.cl/", className = "catalina.servlets.test.MarkAsRejected")
    @ResponseWrapper(localName = "markAsRejectedResponse", targetNamespace = "http://daws.botonpago.hdp.metlife.cl/", className = "catalina.servlets.test.MarkAsRejectedResponse")
    public BotonPago markAsRejected(
            @WebParam(name = "idPago", targetNamespace = "")
                    int idPago,
            @WebParam(name = "idConvenio", targetNamespace = "")
                    int idConvenio,
            @WebParam(name = "reason", targetNamespace = "")
                    String reason,
            @WebParam(name = "notifyMessage", targetNamespace = "")
                    String notifyMessage,
            @WebParam(name = "clientIP", targetNamespace = "")
                    String clientIP);

    /**
     * 
     * @return
     *     returns java.util.List<catalina.servlets.test.ConfiguracionesApp>
     */
    @WebMethod(action = "loadConfig")
    @WebResult(name = "configuraciones", targetNamespace = "")
    @RequestWrapper(localName = "loadConfig", targetNamespace = "http://daws.botonpago.hdp.metlife.cl/", className = "catalina.servlets.test.LoadConfig")
    @ResponseWrapper(localName = "loadConfigResponse", targetNamespace = "http://daws.botonpago.hdp.metlife.cl/", className = "catalina.servlets.test.LoadConfigResponse")
    public List<ConfiguracionesApp> loadConfig();

    /**
     * 
     * @param clientIP
     * @param idPago
     * @return
     *     returns boolean
     */
    @WebMethod(action = "isPayed")
    @WebResult(name = "isPayed", targetNamespace = "")
    @RequestWrapper(localName = "isPayed", targetNamespace = "http://daws.botonpago.hdp.metlife.cl/", className = "catalina.servlets.test.IsPayed")
    @ResponseWrapper(localName = "isPayedResponse", targetNamespace = "http://daws.botonpago.hdp.metlife.cl/", className = "catalina.servlets.test.IsPayedResponse")
    public boolean isPayed(
            @WebParam(name = "idPago", targetNamespace = "")
                    int idPago,
            @WebParam(name = "clientIP", targetNamespace = "")
                    String clientIP);

    /**
     * 
     * @param clientIP
     * @param idPago
     * @param idConvenio
     * @return
     *     returns catalina.servlets.test.BotonPago
     */
    @WebMethod(action = "setAgreementToPayment")
    @WebResult(name = "BotonPago", targetNamespace = "")
    @RequestWrapper(localName = "setAgreementToPayment", targetNamespace = "http://daws.botonpago.hdp.metlife.cl/", className = "catalina.servlets.test.SetAgreementToPayment")
    @ResponseWrapper(localName = "setAgreementToPaymentResponse", targetNamespace = "http://daws.botonpago.hdp.metlife.cl/", className = "catalina.servlets.test.SetAgreementToPaymentResponse")
    public BotonPago setAgreementToPayment(
            @WebParam(name = "idPago", targetNamespace = "")
                    int idPago,
            @WebParam(name = "idConvenio", targetNamespace = "")
                    int idConvenio,
            @WebParam(name = "clientIP", targetNamespace = "")
                    String clientIP);

    /**
     * 
     * @param clientIP
     * @param idPago
     * @param fechaPago
     * @param codTransaccion
     * @param fechaContable
     * @param codAutorizacion
     * @param montoPagado
     * @param notifyMessage
     * @param idBoleta
     * @return
     *     returns boolean
     */
    @WebMethod(action = "addPaymentInfoToInvoice")
    @WebResult(name = "saved", targetNamespace = "")
    @RequestWrapper(localName = "addPaymentInfoToInvoice", targetNamespace = "http://daws.botonpago.hdp.metlife.cl/", className = "catalina.servlets.test.AddPaymentInfoToInvoice")
    @ResponseWrapper(localName = "addPaymentInfoToInvoiceResponse", targetNamespace = "http://daws.botonpago.hdp.metlife.cl/", className = "catalina.servlets.test.AddPaymentInfoToInvoiceResponse")
    public boolean addPaymentInfoToInvoice(
            @WebParam(name = "idPago", targetNamespace = "")
                    int idPago,
            @WebParam(name = "idBoleta", targetNamespace = "")
                    int idBoleta,
            @WebParam(name = "codTransaccion", targetNamespace = "")
                    String codTransaccion,
            @WebParam(name = "codAutorizacion", targetNamespace = "")
                    String codAutorizacion,
            @WebParam(name = "fechaContable", targetNamespace = "")
                    String fechaContable,
            @WebParam(name = "fechaPago", targetNamespace = "")
                    String fechaPago,
            @WebParam(name = "montoPagado", targetNamespace = "")
                    int montoPagado,
            @WebParam(name = "notifyMessage", targetNamespace = "")
                    String notifyMessage,
            @WebParam(name = "clientIP", targetNamespace = "")
                    String clientIP);

    /**
     * 
     * @param campaignName
     * @return
     *     returns catalina.servlets.test.BotonCampaign
     */
    @WebMethod(action = "getCampaignCSS")
    @WebResult(name = "CSS", targetNamespace = "")
    @RequestWrapper(localName = "getCampaignCSS", targetNamespace = "http://daws.botonpago.hdp.metlife.cl/", className = "catalina.servlets.test.GetCampaignCSS")
    @ResponseWrapper(localName = "getCampaignCSSResponse", targetNamespace = "http://daws.botonpago.hdp.metlife.cl/", className = "catalina.servlets.test.GetCampaignCSSResponse")
    public BotonCampaign getCampaignCSS(
            @WebParam(name = "CampaignName", targetNamespace = "")
                    String campaignName);

}
