//
// Generated By:JAX-WS RI IBM 2.1.6 in JDK 6 (JAXB RI IBM JAXB 2.1.10 in JDK 6)
//


package cl.metlife.conciliacion.ws.connectorvi;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="InformacionPago" type="{http://schemas.datacontract.org/2004/07/}pago" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "informacionPago"
})
@XmlRootElement(name = "ConciliarPago", namespace = "http://tempuri.org/")
public class ConciliarPago {

    @XmlElementRef(name = "InformacionPago", namespace = "http://tempuri.org/", type = JAXBElement.class)
    protected JAXBElement<Pago> informacionPago;

    /**
     * Gets the value of the informacionPago property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link Pago }{@code >}
     *     
     */
    public JAXBElement<Pago> getInformacionPago() {
        return informacionPago;
    }

    /**
     * Sets the value of the informacionPago property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link Pago }{@code >}
     *     
     */
    public void setInformacionPago(JAXBElement<Pago> value) {
        this.informacionPago = ((JAXBElement<Pago> ) value);
    }

}
