//
// Generated By:JAX-WS RI IBM 2.1.6 in JDK 6 (JAXB RI IBM JAXB 2.1.10 in JDK 6)
//


package cl.metlife.conciliacion.ws.connectorvi;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

@WebService(name = "IService", targetNamespace = "http://tempuri.org/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface IService {


    /**
     * 
     * @param informacionPago
     * @return
     *     returns cl.metlife.conciliacion.ws.connectorvi.SalidaResultadoConciliacion
     */
    @WebMethod(operationName = "ConciliarPago", action = "http://tempuri.org/IService/ConciliarPago")
    @WebResult(name = "ConciliarPagoResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "ConciliarPago", targetNamespace = "http://tempuri.org/", className = "cl.metlife.conciliacion.ws.connectorvi.ConciliarPago")
    @ResponseWrapper(localName = "ConciliarPagoResponse", targetNamespace = "http://tempuri.org/", className = "cl.metlife.conciliacion.ws.connectorvi.ConciliarPagoResponse")
    public SalidaResultadoConciliacion conciliarPago(
        @WebParam(name = "InformacionPago", targetNamespace = "http://tempuri.org/")
        Pago informacionPago);

}
