//
// Generated By:JAX-WS RI IBM 2.1.6 in JDK 6 (JAXB RI IBM JAXB 2.1.10 in JDK 6)
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://schemas.datacontract.org/2004/07/", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package cl.metlife.conciliacion.ws.connectorvi;
