//
// Generated By:JAX-WS RI IBM 2.1.6 in JDK 6 (JAXB RI IBM JAXB 2.1.10 in JDK 6)
//


package cl.metlife.conciliacion.ws.connectorvi;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for salida_resultadoConciliacion complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="salida_resultadoConciliacion">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="resultadoConciliacion" type="{http://schemas.datacontract.org/2004/07/}resultadoConciliacion" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "salida_resultadoConciliacion", namespace = "http://schemas.datacontract.org/2004/07/", propOrder = {
    "resultadoConciliacion"
})
public class SalidaResultadoConciliacion {

    @XmlElementRef(name = "resultadoConciliacion", namespace = "http://schemas.datacontract.org/2004/07/", type = JAXBElement.class)
    protected JAXBElement<ResultadoConciliacion> resultadoConciliacion;

    /**
     * Gets the value of the resultadoConciliacion property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link ResultadoConciliacion }{@code >}
     *     
     */
    public JAXBElement<ResultadoConciliacion> getResultadoConciliacion() {
        return resultadoConciliacion;
    }

    /**
     * Sets the value of the resultadoConciliacion property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link ResultadoConciliacion }{@code >}
     *     
     */
    public void setResultadoConciliacion(JAXBElement<ResultadoConciliacion> value) {
        this.resultadoConciliacion = ((JAXBElement<ResultadoConciliacion> ) value);
    }

}
