//
// Generated By:JAX-WS RI IBM 2.1.6 in JDK 6 (JAXB RI IBM JAXB 2.1.10 in JDK 6)
//


package cl.metlife.conciliacion.ws.connectorvi;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;

@WebServiceClient(name = "Service", targetNamespace = "http://tempuri.org/", wsdlLocation = "http://mlclwsprd03.alico.corp:97/WS_VI_Conciliation/Conciliador.svc?wsdl")
//@WebServiceClient(name = "Service", targetNamespace = "http://tempuri.org/", wsdlLocation = "http://mlclwsqa03.alico.corp:97/WS_VI_Conciliation/Conciliador.svc?wsdl")
public class Service
    extends javax.xml.ws.Service
{

    private final static URL SERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(cl.metlife.conciliacion.ws.connectorvi.Service.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = cl.metlife.conciliacion.ws.connectorvi.Service.class.getResource(".");
            url = new URL(baseUrl, "http://mlclwsprd03.alico.corp:97/WS_VI_Conciliation/Conciliador.svc?wsdl");
            //url = new URL(baseUrl, "http://mlclwsqa03.alico.corp:97/WS_VI_Conciliation/Conciliador.svc?wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'http://mlclwsprd03.alico.corp:97/WS_VI_Conciliation/Conciliador.svc?wsdl', retrying as a local file");
            //logger.warning("Failed to create URL for the wsdl Location: 'http://mlclwsqa03.alico.corp:97/WS_VI_Conciliation/Conciliador.svc?wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        SERVICE_WSDL_LOCATION = url;
    }

    public Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public Service() {
        super(SERVICE_WSDL_LOCATION, new QName("http://tempuri.org/", "Service"));
    }

    /**
     * 
     * @return
     *     returns IService
     */
    @WebEndpoint(name = "BasicHttpBinding_IService")
    public IService getBasicHttpBindingIService() {
        return super.getPort(new QName("http://tempuri.org/", "BasicHttpBinding_IService"), IService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IService
     */
    @WebEndpoint(name = "BasicHttpBinding_IService")
    public IService getBasicHttpBindingIService(WebServiceFeature... features) {
        return super.getPort(new QName("http://tempuri.org/", "BasicHttpBinding_IService"), IService.class, features);
    }

}
