package cl.metlife.hdp.botonpago.kitpatpass;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.1.6
 * 2016-07-29T18:07:27.873-03:00
 * Generated source version: 3.1.6
 * 
 */
@WebServiceClient(name = "TransbankWrapperService", 
                  wsdlLocation = "file:/F:/workspaces/IdeaProyects/ml-hub-de-pagos/BotonDePagoDMZ/src/cl/metlife/hdp/botonpago/kitpatpass/TransbankWrapper1.wsdl",
                  targetNamespace = "http://transbankwrapper.ws.transbankwrapper.metlife.cl/") 
public class TransbankWrapperService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://transbankwrapper.ws.transbankwrapper.metlife.cl/", "TransbankWrapperService");
    public final static QName TransbankWrapperPort = new QName("http://transbankwrapper.ws.transbankwrapper.metlife.cl/", "TransbankWrapperPort");
    static {
        URL url = null;
        try {
            url = new URL("file:/F:/workspaces/IdeaProyects/ml-hub-de-pagos/BotonDePagoDMZ/src/cl/metlife/hdp/botonpago/kitpatpass/TransbankWrapper1.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(TransbankWrapperService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:/F:/workspaces/IdeaProyects/ml-hub-de-pagos/BotonDePagoDMZ/src/cl/metlife/hdp/botonpago/kitpatpass/TransbankWrapper1.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public TransbankWrapperService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public TransbankWrapperService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public TransbankWrapperService() {
        super(WSDL_LOCATION, SERVICE);
    }


    /**
     *
     * @return
     *     returns TransbankWrapper
     */
    @WebEndpoint(name = "TransbankWrapperPort")
    public TransbankWrapper getTransbankWrapperPort() {
        return super.getPort(TransbankWrapperPort, TransbankWrapper.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns TransbankWrapper
     */
    @WebEndpoint(name = "TransbankWrapperPort")
    public TransbankWrapper getTransbankWrapperPort(WebServiceFeature... features) {
        return super.getPort(TransbankWrapperPort, TransbankWrapper.class, features);
    }

}
