
package cl.metlife.hdp.botonpago.kitpatpass;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;

/**
 * This class was generated by Apache CXF 3.1.6
 * 2016-07-29T18:07:27.794-03:00
 * Generated source version: 3.1.6
 * 
 */
public final class TransbankWrapper_TransbankWrapperPort_Client {

    private static final QName SERVICE_NAME = new QName("http://transbankwrapper.ws.transbankwrapper.metlife.cl/", "TransbankWrapperService");

    private TransbankWrapper_TransbankWrapperPort_Client() {
    }

    public static void main(String args[]) throws Exception {
        URL wsdlURL = TransbankWrapperService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        TransbankWrapperService ss = new TransbankWrapperService(wsdlURL, SERVICE_NAME);
        TransbankWrapper port = ss.getTransbankWrapperPort();  
        
        {
        System.out.println("Invoking getTransactionResult...");
        String _getTransactionResult_tokenInput = "";
        TransactionResultOutput _getTransactionResult__return = port.getTransactionResult(_getTransactionResult_tokenInput);
        System.out.println("getTransactionResult.result=" + _getTransactionResult__return);


        }
        {
        System.out.println("Invoking acknowledgeTransaction...");
        String _acknowledgeTransaction_tokenInput = "";
        port.acknowledgeTransaction(_acknowledgeTransaction_tokenInput);


        }
        {
        System.out.println("Invoking initTransaction...");
        cl.metlife.hdp.botonpago.kitpatpass.WsInitTransactionInput _initTransaction_wsInitTransactionInput = new cl.metlife.hdp.botonpago.kitpatpass.WsInitTransactionInput();
        cl.metlife.hdp.botonpago.kitpatpass.WsInitTransactionOutput _initTransaction__return = port.initTransaction(_initTransaction_wsInitTransactionInput);
        System.out.println("initTransaction.result=" + _initTransaction__return);


        }

        System.exit(0);
    }

}
