package cl.metlife.hdp.botonpago.kitpatpass;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.6
 * 2016-07-29T18:07:27.853-03:00
 * Generated source version: 3.1.6
 * 
 */
@WebService(targetNamespace = "http://transbankwrapper.ws.transbankwrapper.metlife.cl/", name = "TransbankWrapper")
@XmlSeeAlso({ObjectFactory.class})
public interface TransbankWrapper {

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getTransactionResult", targetNamespace = "http://service.wswebpay.webpay.transbank.com/", className = "cl.metlife.hdp.botonpago.kitpatpass.GetTransactionResult")
    @WebMethod
    @ResponseWrapper(localName = "getTransactionResultResponse", targetNamespace = "http://service.wswebpay.webpay.transbank.com/", className = "cl.metlife.hdp.botonpago.kitpatpass.GetTransactionResultResponse")
    public TransactionResultOutput getTransactionResult(
            @WebParam(name = "tokenInput", targetNamespace = "")
                    String tokenInput
    );

    @RequestWrapper(localName = "acknowledgeTransaction", targetNamespace = "http://service.wswebpay.webpay.transbank.com/", className = "cl.metlife.hdp.botonpago.kitpatpass.AcknowledgeTransaction")
    @WebMethod
    @ResponseWrapper(localName = "acknowledgeTransactionResponse", targetNamespace = "http://service.wswebpay.webpay.transbank.com/", className = "cl.metlife.hdp.botonpago.kitpatpass.AcknowledgeTransactionResponse")
    public void acknowledgeTransaction(
            @WebParam(name = "tokenInput", targetNamespace = "")
                    String tokenInput
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "initTransaction", targetNamespace = "http://service.wswebpay.webpay.transbank.com/", className = "cl.metlife.hdp.botonpago.kitpatpass.InitTransaction")
    @WebMethod
    @ResponseWrapper(localName = "initTransactionResponse", targetNamespace = "http://service.wswebpay.webpay.transbank.com/", className = "cl.metlife.hdp.botonpago.kitpatpass.InitTransactionResponse")
    public cl.metlife.hdp.botonpago.kitpatpass.WsInitTransactionOutput initTransaction(
            @WebParam(name = "wsInitTransactionInput", targetNamespace = "")
                    cl.metlife.hdp.botonpago.kitpatpass.WsInitTransactionInput wsInitTransactionInput
    );
}
