//
// Generated By:JAX-WS RI IBM 2.1.6 in JDK 6 (JAXB RI IBM JAXB 2.1.10 in JDK 6)
//


package cl.metlife.conciliacion.ws.parsercaller;

import javax.xml.ws.WebFault;

@WebFault(name = "FileParsingException", targetNamespace = "http://parsepago.ws.conciliacion.hdp.metlife.cl/")
public class FileParsingException_Exception
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private FileParsingException faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public FileParsingException_Exception(String message, FileParsingException faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param faultInfo
     * @param message
     * @param cause
     */
    public FileParsingException_Exception(String message, FileParsingException faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: cl.metlife.hdp.conciliacion.ws.parsercaller.FileParsingException
     */
    public FileParsingException getFaultInfo() {
        return faultInfo;
    }

}
