//
// Generated By:JAX-WS RI IBM 2.1.6 in JDK 6 (JAXB RI IBM JAXB 2.1.10 in JDK 6)
//


package cl.metlife.conciliacion.ws.parsercaller;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the cl.metlife.hdp.conciliacion.ws.parsercaller package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Parse_QNAME = new QName("http://parsepago.ws.conciliacion.hdp.metlife.cl/", "Parse");
    private final static QName _FileParsingException_QNAME = new QName("http://parsepago.ws.conciliacion.hdp.metlife.cl/", "FileParsingException");
    private final static QName _ParseResponse_QNAME = new QName("http://parsepago.ws.conciliacion.hdp.metlife.cl/", "ParseResponse");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: cl.metlife.hdp.conciliacion.ws.parsercaller
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link FileParsingException }
     * 
     */
    public FileParsingException createFileParsingException() {
        return new FileParsingException();
    }

    /**
     * Create an instance of {@link PaymentType }
     * 
     */
    public PaymentType createPaymentType() {
        return new PaymentType();
    }

    /**
     * Create an instance of {@link ParseResponse }
     * 
     */
    public ParseResponse createParseResponse() {
        return new ParseResponse();
    }

    /**
     * Create an instance of {@link ParsedBankFileType }
     * 
     */
    public ParsedBankFileType createParsedBankFileType() {
        return new ParsedBankFileType();
    }

    /**
     * Create an instance of {@link BankFileInfoType }
     * 
     */
    public BankFileInfoType createBankFileInfoType() {
        return new BankFileInfoType();
    }

    /**
     * Create an instance of {@link Parse }
     * 
     */
    public Parse createParse() {
        return new Parse();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Parse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://parsepago.ws.conciliacion.hdp.metlife.cl/", name = "Parse")
    public JAXBElement<Parse> createParse(Parse value) {
        return new JAXBElement<Parse>(_Parse_QNAME, Parse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link FileParsingException }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://parsepago.ws.conciliacion.hdp.metlife.cl/", name = "FileParsingException")
    public JAXBElement<FileParsingException> createFileParsingException(FileParsingException value) {
        return new JAXBElement<FileParsingException>(_FileParsingException_QNAME, FileParsingException.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ParseResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://parsepago.ws.conciliacion.hdp.metlife.cl/", name = "ParseResponse")
    public JAXBElement<ParseResponse> createParseResponse(ParseResponse value) {
        return new JAXBElement<ParseResponse>(_ParseResponse_QNAME, ParseResponse.class, null, value);
    }

}
