//
// Generated By:JAX-WS RI IBM 2.1.6 in JDK 6 (JAXB RI IBM JAXB 2.1.10 in JDK 6)
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://parsepago.ws.conciliacion.hdp.metlife.cl/")
package cl.metlife.hdp.conciliacion.ws.parsercaller;
