//
// Generated By:JAX-WS RI IBM 2.1.6 in JDK 6 (JAXB RI IBM JAXB 2.1.10 in JDK 6)
//


package cl.metlife.conciliacion.ws.parsercaller;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for parsedBankFileType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="parsedBankFileType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="payments" type="{http://parsepago.ws.conciliacion.hdp.metlife.cl/}paymentType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="bankFileInfo" type="{http://parsepago.ws.conciliacion.hdp.metlife.cl/}bankFileInfoType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "parsedBankFileType", namespace = "http://parsepago.ws.conciliacion.hdp.metlife.cl/", propOrder = {
    "payments",
    "bankFileInfo"
})
public class ParsedBankFileType {

    @XmlElement(nillable = true)
    protected List<PaymentType> payments;
    protected BankFileInfoType bankFileInfo;

    /**
     * Gets the value of the payments property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the payments property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPayments().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link PaymentType }
     * 
     * 
     */
    public List<PaymentType> getPayments() {
        if (payments == null) {
            payments = new ArrayList<PaymentType>();
        }
        return this.payments;
    }

    /**
     * Gets the value of the bankFileInfo property.
     * 
     * @return
     *     possible object is
     *     {@link BankFileInfoType }
     *     
     */
    public BankFileInfoType getBankFileInfo() {
        return bankFileInfo;
    }

    /**
     * Sets the value of the bankFileInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link BankFileInfoType }
     *     
     */
    public void setBankFileInfo(BankFileInfoType value) {
        this.bankFileInfo = value;
    }

}
