<?xml version="1.0" encoding="UTF-8"?>
<definitions name="ParserOfficeBankingWS" targetNamespace="http://parsepago.ws.conciliacion.cl.metlife.hdp.metlife.cl/" xmlns:wsp1_2="http://schemas.xmlsoap.org/ws/2004/09/policy" xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:wsp="http://www.w3.org/ns/ws-policy" xmlns:wsam="http://www.w3.org/2007/05/addressing/metadata" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:wsu="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd" xmlns:tns="http://parsepago.ws.conciliacion.hdp.metlife.cl/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
  <types>
    <xsd:schema>
      <xsd:import namespace="http://parsepago.ws.conciliacion.hdp.metlife.cl/" schemaLocation="ParserOfficeBankingWS_schema1.xsd"/>
    </xsd:schema>
  </types>
  <message name="ParseResponse">
    <part name="parameters" element="tns:ParseResponse">
    </part>
  </message>
  <message name="FileParsingException">
    <part name="fault" element="tns:FileParsingException">
    </part>
  </message>
  <message name="Parse">
    <part name="parameters" element="tns:Parse">
    </part>
  </message>
  <portType name="ParserPago">
    <operation name="Parse">
      <input message="tns:Parse" wsam:Action="Parse">
    </input>
      <output message="tns:ParseResponse" wsam:Action="http://parsepago.ws.conciliacion.cl.metlife.hdp.metlife.cl/ParserPago/ParseResponse">
    </output>
      <fault name="FileParsingException" message="tns:FileParsingException" wsam:Action="http://parsepago.ws.conciliacion.cl.metlife.hdp.metlife.cl/ParserPago/Parse/Fault/FileParsingException">
    </fault>
    </operation>
  </portType>
  <binding name="ParserOfficeBankingBinding" type="tns:ParserPago">
    <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <operation name="Parse">
      <soap:operation soapAction="Parse"/>
      <input>
        <soap:body use="literal"/>
      </input>
      <output>
        <soap:body use="literal"/>
      </output>
      <fault name="FileParsingException">
        <soap:fault name="FileParsingException" use="literal"/>
      </fault>
    </operation>
  </binding>
  <service name="ParserOfficeBankingWS">
    <port name="ParserOfficeBanking" binding="tns:ParserOfficeBankingBinding">
      <soap:address location="http://localhost:9080/ParserAnchoFijo/ParserOfficeBankingWS"/>
    </port>
  </service>
</definitions>
