//
// Generated By:JAX-WS RI IBM 2.1.6 in JDK 6 (JAXB RI IBM JAXB 2.1.10 in JDK 6)
//


package cl.metlife.conciliacion.ws.parsercaller;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

@WebService(name = "ParserPago", targetNamespace = "http://parsepago.ws.conciliacion.hdp.metlife.cl/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ParserPago {


    /**
     * 
     * @param parserConfigId
     * @param serializedBankingFile
     * @return
     *     returns cl.metlife.hdp.conciliacion.ws.parsercaller.ParsedBankFileType
     * @throws FileParsingException_Exception
     */
    @WebMethod(operationName = "Parse", action = "Parse")
    @WebResult(name = "Payments", targetNamespace = "")
    @RequestWrapper(localName = "Parse", targetNamespace = "http://parsepago.ws.conciliacion.hdp.metlife.cl/", className = "cl.metlife.hdp.conciliacion.ws.parsercaller.Parse")
    @ResponseWrapper(localName = "ParseResponse", targetNamespace = "http://parsepago.ws.conciliacion.hdp.metlife.cl/", className = "cl.metlife.hdp.conciliacion.ws.parsercaller.ParseResponse")
    public ParsedBankFileType parse(
        @WebParam(name = "SerializedBankingFile", targetNamespace = "")
        String serializedBankingFile,
        @WebParam(name = "ParserConfigId", targetNamespace = "")
        Integer parserConfigId)
        throws FileParsingException_Exception
    ;

}
