//
// Generated By:JAX-WS RI IBM 2.1.6 in JDK 6 (JAXB RI IBM JAXB 2.1.10 in JDK 6)
//


package cl.metlife.conciliacion.ws.parsercaller;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Parse complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Parse">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="SerializedBankingFile" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="ParserConfigId" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Parse", namespace = "http://parsepago.ws.conciliacion.hdp.metlife.cl/", propOrder = {
    "serializedBankingFile",
    "parserConfigId"
})
public class Parse {

    @XmlElement(name = "SerializedBankingFile")
    protected String serializedBankingFile;
    @XmlElement(name = "ParserConfigId")
    protected Integer parserConfigId;

    /**
     * Gets the value of the serializedBankingFile property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSerializedBankingFile() {
        return serializedBankingFile;
    }

    /**
     * Sets the value of the serializedBankingFile property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSerializedBankingFile(String value) {
        this.serializedBankingFile = value;
    }

    /**
     * Gets the value of the parserConfigId property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getParserConfigId() {
        return parserConfigId;
    }

    /**
     * Sets the value of the parserConfigId property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setParserConfigId(Integer value) {
        this.parserConfigId = value;
    }

}
