//
// Generated By:JAX-WS RI IBM 2.1.6 in JDK 6 (JAXB RI IBM JAXB 2.1.10 in JDK 6)
//


package cl.metlife.conciliacion.ws.conciliatorconnector.caller;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;

@WebServiceClient(name = "ConectorConciliadorWS", targetNamespace = "http://ws.conciliacion.hdp.metlife.cl/") //, wsdlLocation = "http://mlclwsdevqa01/Cobranza/CuponDePago/ConectorConciliadorWS.asmx?wsdl")
public class ConectorConciliadorWS
    extends Service
{

    private final static URL CONECTORCONCILIADORWS_WSDL_LOCATION;
    private final static URL BASEURL;
    private final static Logger logger = Logger.getLogger(cl.metlife.conciliacion.ws.conciliatorconnector.caller.ConectorConciliadorWS.class.getName());

    static {
        BASEURL = cl.metlife.conciliacion.ws.conciliatorconnector.caller.ConectorConciliadorWS.class.getResource(".");
        URL url = null;
        try {
            url = new URL(BASEURL, "http://mlclwsdevqa01/Cobranza/CuponDePago/ConectorConciliadorWS.asmx?wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'http://mlclwsdevqa01/Cobranza/CuponDePago/ConectorConciliadorWS.asmx?wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        CONECTORCONCILIADORWS_WSDL_LOCATION = url;
    }

    public ConectorConciliadorWS(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ConectorConciliadorWS() {
        super(CONECTORCONCILIADORWS_WSDL_LOCATION, new QName("http://ws.conciliacion.hdp.metlife.cl/", "ConectorConciliadorWS"));
    }

    public ConectorConciliadorWS(String urlWSDLConciliator) throws MalformedURLException {
        super(new URL(BASEURL, urlWSDLConciliator), new QName("http://ws.conciliacion.hdp.metlife.cl/", "ConectorConciliadorWS"));
    }

    /**
     * 
     * @return
     *     returns ConectorConciliadorWSSoap
     */
    @WebEndpoint(name = "ConectorConciliadorWSSoap")
    public ConectorConciliadorWSSoap getConectorConciliadorWSSoap() {
        return super.getPort(new QName("http://ws.conciliacion.hdp.metlife.cl/", "ConectorConciliadorWSSoap"), ConectorConciliadorWSSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ConectorConciliadorWSSoap
     */
    @WebEndpoint(name = "ConectorConciliadorWSSoap")
    public ConectorConciliadorWSSoap getConectorConciliadorWSSoap(WebServiceFeature... features) {
        return super.getPort(new QName("http://ws.conciliacion.hdp.metlife.cl/", "ConectorConciliadorWSSoap"), ConectorConciliadorWSSoap.class, features);
    }

    /**
     * 
     * @return
     *     returns ConectorConciliadorWSSoap
     */
    @WebEndpoint(name = "ConectorConciliadorWSSoap12")
    public ConectorConciliadorWSSoap getConectorConciliadorWSSoap12() {
        return super.getPort(new QName("http://ws.conciliacion.hdp.metlife.cl/", "ConectorConciliadorWSSoap12"), ConectorConciliadorWSSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ConectorConciliadorWSSoap
     */
    @WebEndpoint(name = "ConectorConciliadorWSSoap12")
    public ConectorConciliadorWSSoap getConectorConciliadorWSSoap12(WebServiceFeature... features) {
        return super.getPort(new QName("http://ws.conciliacion.hdp.metlife.cl/", "ConectorConciliadorWSSoap12"), ConectorConciliadorWSSoap.class, features);
    }

}
