//
// Generated By:JAX-WS RI IBM 2.1.6 in JDK 6 (JAXB RI IBM JAXB 2.1.10 in JDK 6)
//


package cl.metlife.conciliacion.ws.conciliatorconnector.caller;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the cl.metlife.hdp.conciliacion.ws.conciliatorconnector.caller package.
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: cl.metlife.hdp.conciliacion.ws.conciliatorconnector.caller
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ConciliarPago }
     * 
     */
    public ConciliarPago createConciliarPago() {
        return new ConciliarPago();
    }

    /**
     * Create an instance of {@link Pago }
     * 
     */
    public Pago createPago() {
        return new Pago();
    }

    /**
     * Create an instance of {@link ConciliarPagoResponse }
     * 
     */
    public ConciliarPagoResponse createConciliarPagoResponse() {
        return new ConciliarPagoResponse();
    }

    /**
     * Create an instance of {@link ResultadoConciliacion }
     * 
     */
    public ResultadoConciliacion createResultadoConciliacion() {
        return new ResultadoConciliacion();
    }

}
