//
// Generated By:JAX-WS RI IBM 2.1.6 in JDK 6 (JAXB RI IBM JAXB 2.1.10 in JDK 6)
//


package cl.metlife.conciliacion.ws.conciliatorconnector.caller;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for pago complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="pago">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="NumeroConvenio" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0" form="unqualified"/>
 *         &lt;element name="CuentaControl" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0" form="unqualified"/>
 *         &lt;element name="TipoDocumentoPago" type="{http://ws.conciliacion.hdp.metlife.cl/}tipoDocumento" form="unqualified"/>
 *         &lt;element name="NumeroDocumento" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0" form="unqualified"/>
 *         &lt;element name="NumeroProducto" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0" form="unqualified"/>
 *         &lt;element name="MesCuota" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0" form="unqualified"/>
 *         &lt;element name="AgnoCuota" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0" form="unqualified"/>
 *         &lt;element name="MontoPagado" type="{http://www.w3.org/2001/XMLSchema}double" form="unqualified"/>
 *         &lt;element name="CodigoMoneda" type="{http://ws.conciliacion.hdp.metlife.cl/}moneda" form="unqualified"/>
 *         &lt;element name="FechaPago" type="{http://www.w3.org/2001/XMLSchema}dateTime" form="unqualified"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "pago", namespace = "http://ws.conciliacion.hdp.metlife.cl/", propOrder = {
    "numeroConvenio",
    "cuentaControl",
    "tipoDocumentoPago",
    "numeroDocumento",
    "numeroProducto",
    "mesCuota",
    "agnoCuota",
    "montoPagado",
    "codigoMoneda",
    "fechaPago"
})
public class Pago {

    @XmlElement(name = "NumeroConvenio")
    protected String numeroConvenio;
    @XmlElement(name = "CuentaControl")
    protected String cuentaControl;
    @XmlElement(name = "TipoDocumentoPago")
    protected TipoDocumento tipoDocumentoPago;
    @XmlElement(name = "NumeroDocumento", required = true)
    protected String numeroDocumento;
    @XmlElement(name = "NumeroProducto", required = true)
    protected String numeroProducto;
    @XmlElement(name = "MesCuota", required = true)
    protected String mesCuota;
    @XmlElement(name = "AgnoCuota", required = true)
    protected String agnoCuota;
    @XmlElement(name = "MontoPagado", required = true)
    protected double montoPagado;
    @XmlElement(name = "CodigoMoneda", required = true)
    protected Moneda codigoMoneda;
    @XmlElement(name = "FechaPago", required = true)
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar fechaPago;

    public Pago(){}

    public Pago(String numeroConvenio, String cuentaControl, TipoDocumento tipoDocumentoPago,
                String numeroDocumento, String numeroProducto, String mesCuota, String agnoCuota,
                double montoPagado, Moneda codigoMoneda, XMLGregorianCalendar fechaPago) {
        this.numeroConvenio = numeroConvenio;
        this.cuentaControl = cuentaControl;
        this.tipoDocumentoPago = tipoDocumentoPago;
        this.numeroDocumento = numeroDocumento;
        this.numeroProducto = numeroProducto;
        this.mesCuota = mesCuota;
        this.agnoCuota = agnoCuota;
        this.montoPagado = montoPagado;
        this.codigoMoneda = codigoMoneda;
        this.fechaPago = fechaPago;
    }

    /**
     * Gets the value of the numeroConvenio property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNumeroConvenio() {
        return numeroConvenio;
    }

    /**
     * Sets the value of the numeroConvenio property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNumeroConvenio(String value) {
        this.numeroConvenio = value;
    }

    /**
     * Gets the value of the cuentaControl property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCuentaControl() {
        return cuentaControl;
    }

    /**
     * Sets the value of the cuentaControl property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCuentaControl(String value) {
        this.cuentaControl = value;
    }

    /**
     * Gets the value of the tipoDocumentoPago property.
     * 
     * @return
     *     possible object is
     *     {@link TipoDocumento }
     *     
     */
    public TipoDocumento getTipoDocumentoPago() {
        return tipoDocumentoPago;
    }

    /**
     * Sets the value of the tipoDocumentoPago property.
     * 
     * @param value
     *     allowed object is
     *     {@link TipoDocumento }
     *     
     */
    public void setTipoDocumentoPago(TipoDocumento value) {
        this.tipoDocumentoPago = value;
    }

    /**
     * Gets the value of the numeroDocumento property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNumeroDocumento() {
        return numeroDocumento;
    }

    /**
     * Sets the value of the numeroDocumento property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNumeroDocumento(String value) {
        this.numeroDocumento = value;
    }

    /**
     * Gets the value of the numeroProducto property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNumeroProducto() {
        return numeroProducto;
    }

    /**
     * Sets the value of the numeroProducto property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNumeroProducto(String value) {
        this.numeroProducto = value;
    }

    /**
     * Gets the value of the mesCuota property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMesCuota() {
        return mesCuota;
    }

    /**
     * Sets the value of the mesCuota property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMesCuota(String value) {
        this.mesCuota = value;
    }

    /**
     * Gets the value of the agnoCuota property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAgnoCuota() {
        return agnoCuota;
    }

    /**
     * Sets the value of the agnoCuota property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAgnoCuota(String value) {
        this.agnoCuota = value;
    }

    /**
     * Gets the value of the montoPagado property.
     * 
     */
    public double getMontoPagado() {
        return montoPagado;
    }

    /**
     * Sets the value of the montoPagado property.
     * 
     */
    public void setMontoPagado(double value) {
        this.montoPagado = value;
    }

    /**
     * Gets the value of the codigoMoneda property.
     * 
     * @return
     *     possible object is
     *     {@link Moneda }
     *     
     */
    public Moneda getCodigoMoneda() {
        return codigoMoneda;
    }

    /**
     * Sets the value of the codigoMoneda property.
     * 
     * @param value
     *     allowed object is
     *     {@link Moneda }
     *     
     */
    public void setCodigoMoneda(Moneda value) {
        this.codigoMoneda = value;
    }

    /**
     * Gets the value of the fechaPago property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getFechaPago() {
        return fechaPago;
    }

    /**
     * Sets the value of the fechaPago property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setFechaPago(XMLGregorianCalendar value) {
        this.fechaPago = value;
    }

}
