//
// Generated By:JAX-WS RI IBM 2.1.6 in JDK 6 (JAXB RI IBM JAXB 2.1.10 in JDK 6)
//


package cl.metlife.conciliacion.ws.conciliatorconnector.caller;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for resultadoConciliacion complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="resultadoConciliacion">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="NuevoEstado" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0" form="unqualified"/>
 *         &lt;element name="DetalleEstado" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0" form="unqualified"/>
 *         &lt;element name="NumeroFactura" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0" form="unqualified"/>
 *         &lt;element name="CuentaControl" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0" form="unqualified"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "resultadoConciliacion", namespace = "http://ws.conciliacion.hdp.metlife.cl/", propOrder = {
    "nuevoEstado",
    "detalleEstado",
    "numeroFactura",
    "cuentaControl"
})
public class ResultadoConciliacion {

    @XmlElement(name = "NuevoEstado")
    protected String nuevoEstado;
    @XmlElement(name = "DetalleEstado")
    protected String detalleEstado;
    @XmlElement(name = "NumeroFactura")
    protected String numeroFactura;
    @XmlElement(name = "CuentaControl")
    protected String cuentaControl;

    /**
     * Gets the value of the nuevoEstado property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNuevoEstado() {
        return nuevoEstado;
    }

    /**
     * Sets the value of the nuevoEstado property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNuevoEstado(String value) {
        this.nuevoEstado = value;
    }

    /**
     * Gets the value of the detalleEstado property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDetalleEstado() {
        return detalleEstado;
    }

    /**
     * Sets the value of the detalleEstado property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDetalleEstado(String value) {
        this.detalleEstado = value;
    }

    /**
     * Gets the value of the numeroFactura property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNumeroFactura() {
        return numeroFactura;
    }

    /**
     * Sets the value of the numeroFactura property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNumeroFactura(String value) {
        this.numeroFactura = value;
    }

    /**
     * Gets the value of the cuentaControl property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCuentaControl() {
        return cuentaControl;
    }

    /**
     * Sets the value of the cuentaControl property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCuentaControl(String value) {
        this.cuentaControl = value;
    }

}
